Repository googleapis/elixir-google-api, pull requests merged in 2019-03, with the labels that each got.

#989 Regenerate StreetViewPublish client
  clients/street_view_publish/lib/google_api/street_view_publish/v1/api/photo.ex
  clients/street_view_publish/lib/google_api/street_view_publish/v1/api/photos.ex
  clients/street_view_publish/lib/google_api/street_view_publish/v1/model/batch_delete_photos_request.ex
  clients/street_view_publish/lib/google_api/street_view_publish/v1/model/list_photos_response.ex
  clients/street_view_publish/lib/google_api/street_view_publish/v1/model/photo.ex
  clients/street_view_publish/lib/google_api/street_view_publish/v1/model/pose.ex
  clients/street_view_publish/lib/google_api/street_view_publish/v1/model/update_photo_request.ex
  clients/street_view_publish/mix.exs
Labels: :rotating_light:, cla: yes

#990 Regenerate Sheets client
  clients/sheets/lib/google_api/sheets/v4/model/color.ex
  clients/sheets/mix.exs
Labels: cla: yes

#992 Regenerate Drive client
  clients/drive/lib/google_api/drive/v3/api/revisions.ex
Labels: cla: yes

#988 Regenerate SourceRepo client
  clients/source_repo/lib/google_api/source_repo/v1/model/binding.ex
  clients/source_repo/mix.exs
Labels: :rotating_light:, cla: yes

#991 Regenerate CloudIot client
  clients/cloud_iot/lib/google_api/cloud_iot/v1/model/binding.ex
  clients/cloud_iot/mix.exs
Labels: cla: yes

#993 Regenerate Vault client
  clients/vault/lib/google_api/vault/v1/model/mail_export_options.ex
  clients/vault/mix.exs
Labels: cla: yes

#916 Regenerate CloudFunctions client
  clients/cloud_functions/lib/google_api/cloud_functions/v1/api/operations.ex
  clients/cloud_functions/mix.exs
Labels: :rotating_light:, cla: yes

#987 Regenerate Reseller client
  clients/reseller/lib/google_api/reseller/v1/api/subscriptions.ex
  clients/reseller/lib/google_api/reseller/v1/model/change_plan_request.ex
  clients/reseller/lib/google_api/reseller/v1/model/customer.ex
  clients/reseller/lib/google_api/reseller/v1/model/seats.ex
  clients/reseller/lib/google_api/reseller/v1/model/subscription_plan.ex
  clients/reseller/lib/google_api/reseller/v1/model/subscription_plan_commitment_interval.ex
  clients/reseller/mix.exs
Labels: :rotating_light:, cla: yes

#917 Regenerate Compute client
  clients/compute/lib/google_api/compute/v1/api/instance_templates.ex
  clients/compute/lib/google_api/compute/v1/api/node_groups.ex
  clients/compute/lib/google_api/compute/v1/model/accelerator_config.ex
  clients/compute/lib/google_api/compute/v1/model/attached_disk.ex
  clients/compute/lib/google_api/compute/v1/model/autoscaling_policy_load_balancing_utilization.ex
  clients/compute/lib/google_api/compute/v1/model/disk.ex
  clients/compute/lib/google_api/compute/v1/model/image.ex
  clients/compute/lib/google_api/compute/v1/model/instance.ex
  clients/compute/lib/google_api/compute/v1/model/instance_group_manager.ex
  clients/compute/lib/google_api/compute/v1/model/instance_group_manager_auto_healing_policy.ex
  clients/compute/lib/google_api/compute/v1/model/interconnect.ex
  clients/compute/lib/google_api/compute/v1/model/interconnect_location.ex
  clients/compute/lib/google_api/compute/v1/model/quota.ex
  clients/compute/mix.exs
Labels: :rotating_light:, cla: yes

#986 Regenerate CloudKMS client
  clients/cloud_kms/lib/google_api/cloud_kms/v1/model/binding.ex
  clients/cloud_kms/lib/google_api/cloud_kms/v1/model/key_operation_attestation.ex
  clients/cloud_kms/mix.exs
Labels: :rotating_light:, cla: yes

#985 Regenerate Tasks client
  clients/tasks/lib/google_api/tasks/v1/api/tasklists.ex
  clients/tasks/lib/google_api/tasks/v1/api/tasks.ex
  clients/tasks/mix.exs
Labels: :rotating_light:, cla: yes

#984 Regenerate People client
  clients/people/lib/google_api/people/v1/connection.ex
  clients/people/mix.exs
Labels: :rotating_light:, cla: yes

#983 Regenerate PlusDomains client
  clients/plus_domains/lib/google_api/plus_domains/v1/connection.ex
  clients/plus_domains/mix.exs
Labels: :rotating_light:, cla: yes

#982 Regenerate Plus client
  clients/plus/lib/google_api/plus/v1/connection.ex
  clients/plus/mix.exs
Labels: :rotating_light:, cla: yes

#981 Regenerate OAuth2 client
  clients/o_auth2/lib/google_api/o_auth2/v2/connection.ex
  clients/o_auth2/mix.exs
Labels: :rotating_light:, cla: yes

#980 Regenerate GamesManagement client
  clients/games_management/lib/google_api/games_management/v1management/connection.ex
  clients/games_management/mix.exs
Labels: :rotating_light:, cla: yes

#921 Regenerate Gmail client
  clients/gmail/lib/google_api/gmail/v1/model/delegate.ex
  clients/gmail/mix.exs
Labels: :rotating_light:, cla: yes

#923 Regenerate ServiceConsumerManagement client
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/api/services.ex
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/model/backend_rule.ex
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/model/monitoring.ex
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/model/monitoring_destination.ex
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/model/service.ex
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/model/tenant_resource.ex
Labels: :rotating_light:, cla: yes

#924 Regenerate ServiceControl client
  clients/service_control/lib/google_api/service_control/v1/model/resource_location.ex
  clients/service_control/mix.exs
Labels: :rotating_light:, cla: yes

#925 Regenerate ServiceManagement client
  clients/service_management/lib/google_api/service_management/v1/model/monitoring.ex
  clients/service_management/lib/google_api/service_management/v1/model/monitoring_destination.ex
  clients/service_management/lib/google_api/service_management/v1/model/service.ex
  clients/service_management/mix.exs
Labels: :rotating_light:, cla: yes

#926 Regenerate ServiceUser client
  clients/service_user/lib/google_api/service_user/v1/model/monitoring.ex
  clients/service_user/lib/google_api/service_user/v1/model/monitoring_destination.ex
  clients/service_user/lib/google_api/service_user/v1/model/service.ex
  clients/service_user/mix.exs
Labels: :rotating_light:, cla: yes

#978 Regenerate Dataproc client
  clients/dataproc/lib/google_api/dataproc/v1/model/job_reference.ex
  clients/dataproc/lib/google_api/dataproc/v1/model/software_config.ex
  clients/dataproc/mix.exs
Labels: :rotating_light:, cla: yes

#928 Regenerate Testing client
  clients/testing/lib/google_api/testing/v1/model/ios_xc_test.ex
  clients/testing/lib/google_api/testing/v1/model/test_matrix.ex
Labels: :rotating_light:, cla: yes

#929 Regenerate WebSecurityScanner client
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1alpha/model/scan_config.ex
  clients/web_security_scanner/mix.exs
Labels: :rotating_light:, cla: yes

#930 Regenerate YouTubeAnalytics client
  clients/you_tube_analytics/lib/google_api/you_tube_analytics/v1/model/result_table.ex
  clients/you_tube_analytics/mix.exs
Labels: :rotating_light:, cla: yes

#931 Regenerate Chat client
  clients/chat/lib/google_api/chat/v1/api/spaces.ex
  clients/chat/mix.exs
Labels: :rotating_light:, cla: yes

#842 Fix path variable encoding
  clients/test_client/lib/google_api/test_client/v1/api/objects.ex
  clients/test_client/lib/google_api/test_client/v2/api/objects.ex
  clients/test_client/test/api_test.exs
  template/gax/api.mustache
Labels: :rotating_light:, cla: yes

#934 Regenerate Composer client
  clients/composer/lib/google_api/composer/v1beta1/api/projects.ex
  clients/composer/lib/google_api/composer/v1beta1/model/image_version.ex
  clients/composer/lib/google_api/composer/v1beta1/model/list_image_versions_response.ex
  clients/composer/mix.exs
Labels: :rotating_light:, cla: yes

#936 Regenerate Analytics client
  clients/analytics/lib/google_api/analytics/v3/api/management.ex
  clients/analytics/lib/google_api/analytics/v3/model/account_tree_request.ex
  clients/analytics/lib/google_api/analytics/v3/model/account_tree_response.ex
  clients/analytics/lib/google_api/analytics/v3/model/ad_words_account.ex
  clients/analytics/lib/google_api/analytics/v3/model/entity_ad_words_link.ex
  clients/analytics/lib/google_api/analytics/v3/model/entity_ad_words_links.ex
  clients/analytics/lib/google_api/analytics/v3/model/linked_foreign_account.ex
  clients/analytics/mix.exs
Labels: :rotating_light:, cla: yes

#937 Regenerate Script client
  clients/script/lib/google_api/script/v1/model/execution_request.ex
  clients/script/mix.exs
Labels: :rotating_light:, cla: yes

#938 Regenerate VideoIntelligence client
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p2beta1_object_tracking_annotation.ex
  clients/video_intelligence/mix.exs
Labels: :rotating_light:, cla: yes

#939 Regenerate Fitness client
  clients/fitness/lib/google_api/fitness/v1/model/aggregate_request.ex
  clients/fitness/lib/google_api/fitness/v1/model/data_source.ex
  clients/fitness/lib/google_api/fitness/v1/model/dataset.ex
  clients/fitness/mix.exs
Labels: :rotating_light:, cla: yes

#940 Regenerate CloudBilling client
  clients/cloud_billing/lib/google_api/cloud_billing/v1/model/service.ex
  clients/cloud_billing/mix.exs
Labels: :rotating_light:, cla: yes

#941 Regenerate CloudBuild client
  clients/cloud_build/lib/google_api/cloud_build/v1/model/source_provenance.ex
  clients/cloud_build/mix.exs
Labels: :rotating_light:, cla: yes

#944 Regenerate IAM client
  clients/iam/lib/google_api/iam/v1/api/projects.ex
  clients/iam/lib/google_api/iam/v1/model/patch_service_account_request.ex
  clients/iam/mix.exs
Labels: :rotating_light:, cla: yes

#945 Regenerate MachineLearning client
  clients/machine_learning/lib/google_api/machine_learning/v1/model/google_api__http_body.ex
  clients/machine_learning/lib/google_api/machine_learning/v1/model/google_cloud_ml_v1__prediction_input.ex
  clients/machine_learning/lib/google_api/machine_learning/v1/model/google_cloud_ml_v1__training_input.ex
  clients/machine_learning/mix.exs
Labels: :rotating_light:, cla: yes

#946 Regenerate Speech client
  clients/speech/lib/google_api/speech/v1/api/projects.ex
  clients/speech/lib/google_api/speech/v1/model/recognition_config.ex
  clients/speech/lib/google_api/speech/v1/model/speech_recognition_result.ex
  clients/speech/mix.exs
Labels: :rotating_light:, cla: yes

#947 Regenerate BigQuery client
  clients/big_query/lib/google_api/big_query/v2/model/external_data_configuration.ex
  clients/big_query/lib/google_api/big_query/v2/model/job_configuration_load.ex
  clients/big_query/mix.exs
Labels: :rotating_light:, cla: yes

#948 Regenerate Logging client
  clients/logging/lib/google_api/logging/v2/api/billing_accounts.ex
  clients/logging/lib/google_api/logging/v2/api/folders.ex
  clients/logging/lib/google_api/logging/v2/api/organizations.ex
  clients/logging/lib/google_api/logging/v2/api/projects.ex
  clients/logging/lib/google_api/logging/v2/api/sinks.ex
  clients/logging/lib/google_api/logging/v2/model/log_entry.ex
  clients/logging/lib/google_api/logging/v2/model/log_exclusion.ex
  clients/logging/lib/google_api/logging/v2/model/log_metric.ex
  clients/logging/lib/google_api/logging/v2/model/log_sink.ex
  clients/logging/mix.exs
Labels: :rotating_light:, cla: yes

#953 Regenerate AndroidPublisher client
  clients/android_publisher/lib/google_api/android_publisher/v2/model/product_purchase.ex
  clients/android_publisher/mix.exs
Labels: :rotating_light:, cla: yes

#954 Regenerate DoubleClickBidManager client
  clients/double_click_bid_manager/lib/google_api/double_click_bid_manager/v1/model/filter_pair.ex
  clients/double_click_bid_manager/mix.exs
Labels: :rotating_light:, cla: yes

#955 Regenerate Content client
  clients/content/lib/google_api/content/v2/api/accountstatuses.ex
  clients/content/lib/google_api/content/v2/model/order.ex
  clients/content/lib/google_api/content/v2/model/orderpayments_notify_auth_approved_request.ex
  clients/content/lib/google_api/content/v2/model/test_order_line_item.ex
  clients/content/lib/google_api/content/v2/model/test_order_line_item_product.ex
  clients/content/mix.exs
Labels: :rotating_light:, cla: yes

#956 Regenerate Monitoring client
  clients/monitoring/lib/google_api/monitoring/v3/model/uptime_check_config.ex
  clients/monitoring/mix.exs
Labels: :rotating_light:, cla: yes

#976 Update the storage path
  clients/gax/test/gax/request_test.exs
Labels: :rotating_light:, cla: yes

#975 Regenerate SQLAdmin client
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/export_context.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/export_context_csv_export_options.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/flag.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/import_context.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/import_context_csv_import_options.ex
  clients/sql_admin/mix.exs
Labels: :rotating_light:, cla: yes

#974 Regenerate Genomics client
  clients/genomics/lib/google_api/genomics/v1/api/operations.ex
  clients/genomics/mix.exs
Labels: :rotating_light:, cla: yes

#973 Regenerate CloudTasks client
  clients/cloud_tasks/lib/google_api/cloud_tasks/v2beta2/model/task_status.ex
  clients/cloud_tasks/mix.exs
Labels: :rotating_light:, cla: yes

#971 Regenerate Storage client
  clients/storage/lib/google_api/storage/v1/model/bucket_iam_configuration_bucket_policy_only.ex
  clients/storage/lib/google_api/storage/v1/model/expr.ex
  clients/storage/lib/google_api/storage/v1/model/policy_bindings.ex
  clients/storage/mix.exs
Labels: :rotating_light:, cla: yes

#970 Regenerate FirebaseDynamicLinks client
  clients/firebase_dynamic_links/lib/google_api/firebase_dynamic_links/v1/model/app_preview.ex
  clients/firebase_dynamic_links/lib/google_api/firebase_dynamic_links/v1/model/dynamic_link_info.ex
  clients/firebase_dynamic_links/mix.exs
Labels: :rotating_light:, cla: yes

#969 Regenerate AppEngine client
  clients/app_engine/lib/google_api/app_engine/v1/model/network.ex
  clients/app_engine/mix.exs
Labels: :rotating_light:, cla: yes

#967 Regenerate Games client
  clients/games/lib/google_api/games/v1/connection.ex
  clients/games/mix.exs
Labels: :rotating_light:, cla: yes

#966 Regenerate DFAReporting client
  clients/dfa_reporting/lib/google_api/dfa_reporting/v28/model/floodlight_activities_generate_tag_response.ex
  clients/dfa_reporting/mix.exs
Labels: :rotating_light:, cla: yes

#964 Regenerate IAMCredentials client
  clients/iam_credentials/lib/google_api/iam_credentials/v1/model/generate_identity_binding_access_token_request.ex
  clients/iam_credentials/mix.exs
Labels: :rotating_light:, cla: yes

#963 Regenerate Dataflow client
  clients/dataflow/lib/google_api/dataflow/v1b3/model/lease_work_item_request.ex
  clients/dataflow/lib/google_api/dataflow/v1b3/model/lease_work_item_response.ex
  clients/dataflow/lib/google_api/dataflow/v1b3/model/report_work_item_status_request.ex
  clients/dataflow/lib/google_api/dataflow/v1b3/model/report_work_item_status_response.ex
  clients/dataflow/lib/google_api/dataflow/v1b3/model/streaming_computation_config.ex
  clients/dataflow/mix.exs
Labels: :rotating_light:, cla: yes

#962 Regenerate CloudResourceManager client
  clients/cloud_resource_manager/lib/google_api/cloud_resource_manager/v1/api/organizations.ex
  clients/cloud_resource_manager/mix.exs
Labels: :rotating_light:, cla: yes

#960 Regenerate Redis client
  clients/redis/lib/google_api/redis/v1beta1/model/instance.ex
Labels: :rotating_light:, cla: yes

#959 Regenerate Books client
  clients/books/lib/google_api/books/v1/model/notification.ex
  clients/books/mix.exs
Labels: :rotating_light:, cla: yes

#958 Regenerate ToolResults client
  clients/tool_results/lib/google_api/tool_results/v1beta3/model/outcome.ex
  clients/tool_results/mix.exs
Labels: :rotating_light:, cla: yes

#957 Regenerate PubSub client
  clients/pub_sub/lib/google_api/pub_sub/v1/api/projects.ex
  clients/pub_sub/mix.exs
Labels: :rotating_light:, cla: yes

#1106 Regenerate AnalyticsReporting client
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/api/user_activity.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/activity.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/custom_dimension.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/ecommerce_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/event_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/goal_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/goal_set_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/pageview_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/product_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/screenview_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/search_user_activity_request.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/search_user_activity_response.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/transaction_data.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/user.ex
  clients/analytics_reporting/lib/google_api/analytics_reporting/v4/model/user_activity_session.ex
  clients/analytics_reporting/mix.exs
Labels: :rotating_light:, cla: yes

#1105 Fix to match even already parsed DateTime
  clients/gax/lib/google_api/gax/model_base.ex
Labels: :rotating_light:, cla: yes

#1104 Regenerate YouTubeReporting client
  clients/you_tube_reporting/lib/google_api/you_tube_reporting/v1/api/jobs.ex
  clients/you_tube_reporting/lib/google_api/you_tube_reporting/v1/api/media.ex
  clients/you_tube_reporting/mix.exs
Labels: :rotating_light:, cla: yes, help wanted

#1103 Regenerate Webmaster client
  clients/webmaster/lib/google_api/webmaster/v3/api/searchanalytics.ex
  clients/webmaster/lib/google_api/webmaster/v3/api/sitemaps.ex
  clients/webmaster/lib/google_api/webmaster/v3/api/sites.ex
  clients/webmaster/lib/google_api/webmaster/v3/api/urlcrawlerrorscounts.ex
  clients/webmaster/lib/google_api/webmaster/v3/api/urlcrawlerrorssamples.ex
  clients/webmaster/mix.exs
Labels: :rotating_light:, cla: yes

#1102 Regenerate WebSecurityScanner client
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1alpha/api/projects.ex
Labels: :rotating_light:, cla: yes

#1095 Regenerate VideoIntelligence client
  clients/video_intelligence/lib/google_api/video_intelligence/v1/api/operations.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_label_detection_config.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_normalized_bounding_box.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_normalized_bounding_poly.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_normalized_vertex.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_object_tracking_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_object_tracking_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_text_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_text_detection_config.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_text_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_text_segment.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_video_annotation_results.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1_video_context.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_normalized_bounding_box.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_normalized_bounding_poly.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_normalized_vertex.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_object_tracking_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_object_tracking_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_text_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_text_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_text_segment.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1beta2_video_annotation_results.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_normalized_bounding_box.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_normalized_bounding_poly.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_normalized_vertex.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_object_tracking_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_object_tracking_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_text_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_text_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_text_segment.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p1beta1_video_annotation_results.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_annotate_video_progress.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_annotate_video_response.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_entity.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_explicit_content_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_explicit_content_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_label_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_label_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_label_segment.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_normalized_bounding_box.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_normalized_bounding_poly.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_normalized_vertex.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_object_tracking_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_object_tracking_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_speech_recognition_alternative.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_speech_transcription.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_streaming_annotate_video_response.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_streaming_video_annotation_results.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_text_annotation.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_text_frame.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_text_segment.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_video_annotation_progress.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_video_annotation_results.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_video_segment.ex
  clients/video_intelligence/lib/google_api/video_intelligence/v1/model/google_cloud_videointelligence_v1p3beta1_word_info.ex
  clients/video_intelligence/mix.exs
Labels: :rotating_light:, cla: yes

#1094 Regenerate Vault client
  clients/vault/lib/google_api/vault/v1/api/matters.ex
  clients/vault/mix.exs
Labels: :rotating_light:, cla: yes

#1093 Regenerate ToolResults client
  clients/tool_results/lib/google_api/tool_results/v1beta3/api/projects.ex
  clients/tool_results/lib/google_api/tool_results/v1beta3/model/individual_outcome.ex
  clients/tool_results/lib/google_api/tool_results/v1beta3/model/multi_step.ex
  clients/tool_results/lib/google_api/tool_results/v1beta3/model/primary_step.ex
  clients/tool_results/lib/google_api/tool_results/v1beta3/model/step.ex
  clients/tool_results/lib/google_api/tool_results/v1beta3/model/test_issue.ex
  clients/tool_results/mix.exs
Labels: :rotating_light:, cla: yes

#1092 Regenerate Testing client
  clients/testing/lib/google_api/testing/v1/api/projects.ex
  clients/testing/lib/google_api/testing/v1/api/test_environment_catalog.ex
  clients/testing/lib/google_api/testing/v1/model/android_device.ex
  clients/testing/lib/google_api/testing/v1/model/android_matrix.ex
  clients/testing/lib/google_api/testing/v1/model/ios_device.ex
  clients/testing/lib/google_api/testing/v1/model/ios_xc_test.ex
  clients/testing/lib/google_api/testing/v1/model/robo_directive.ex
  clients/testing/lib/google_api/testing/v1/model/robo_starting_intent.ex
  clients/testing/lib/google_api/testing/v1/model/test_matrix.ex
Labels: :rotating_light:, cla: yes

#1091 Regenerate Tasks client
  clients/tasks/lib/google_api/tasks/v1/api/tasklists.ex
  clients/tasks/lib/google_api/tasks/v1/api/tasks.ex
  clients/tasks/mix.exs
Labels: :rotating_light:, cla: yes

#979 Regenerate TagManager client
  clients/tag_manager/lib/google_api/tag_manager/v2/api/accounts.ex
  clients/tag_manager/lib/google_api/tag_manager/v2/model/container_version.ex
  clients/tag_manager/lib/google_api/tag_manager/v2/model/container_version_header.ex
  clients/tag_manager/lib/google_api/tag_manager/v2/model/custom_template.ex
  clients/tag_manager/lib/google_api/tag_manager/v2/model/list_zones_response.ex
  clients/tag_manager/lib/google_api/tag_manager/v2/model/revert_zone_response.ex
  clients/tag_manager/lib/google_api/tag_manager/v2/model/variable.ex
  clients/tag_manager/lib/google_api/tag_manager/v2/model/variable_format_value.ex
  clients/tag_manager/mix.exs
Labels: :rotating_light:, cla: yes

#995 Regenerate AdExchangeBuyer client
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/budget.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/creatives.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/marketplacedeals.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/marketplacenotes.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/marketplaceprivateauction.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/pretargeting_config.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/products.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v14/api/proposals.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v2beta1/api/accounts.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v2beta1/api/bidders.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v2beta1/model/creative.ex
  clients/ad_exchange_buyer/lib/google_api/ad_exchange_buyer/v2beta1/model/pause_proposal_request.ex
  clients/ad_exchange_buyer/mix.exs
Labels: :rotating_light:, cla: yes

#996 Regenerate AdExperienceReport client
  clients/ad_experience_report/lib/google_api/ad_experience_report/v1/api/sites.ex
  clients/ad_experience_report/mix.exs
Labels: :rotating_light:, cla: yes

#1090 Regenerate TPU client
  clients/tpu/lib/google_api/tpu/v1/api/projects.ex
  clients/tpu/lib/google_api/tpu/v1/model/node.ex
Labels: :rotating_light:, cla: yes

#1089 Regenerate Surveys client
  clients/surveys/lib/google_api/surveys/v2/api/results.ex
  clients/surveys/lib/google_api/surveys/v2/api/surveys.ex
  clients/surveys/mix.exs
Labels: :rotating_light:, cla: yes

#1088 Regenerate StreetViewPublish client
  clients/street_view_publish/lib/google_api/street_view_publish/v1/api/photo.ex
  clients/street_view_publish/lib/google_api/street_view_publish/v1/model/photo.ex
  clients/street_view_publish/mix.exs
Labels: :rotating_light:, cla: yes

#1087 Regenerate StorageTransfer client
  clients/storage_transfer/lib/google_api/storage_transfer/v1/api/google_service_accounts.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/api/transfer_jobs.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/api/transfer_operations.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/error_summary.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/object_conditions.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/transfer_job.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/transfer_operation.ex
  clients/storage_transfer/mix.exs
Labels: :rotating_light:, cla: yes

#1086 Regenerate Storage client
  clients/storage/lib/google_api/storage/v1/api/bucket_access_controls.ex
  clients/storage/lib/google_api/storage/v1/api/buckets.ex
  clients/storage/lib/google_api/storage/v1/api/default_object_access_controls.ex
  clients/storage/lib/google_api/storage/v1/api/notifications.ex
  clients/storage/lib/google_api/storage/v1/api/object_access_controls.ex
  clients/storage/lib/google_api/storage/v1/api/objects.ex
  clients/storage/lib/google_api/storage/v1/api/projects.ex
  clients/storage/mix.exs
Labels: :rotating_light:, cla: yes

#1085 Regenerate Speech client
  clients/speech/config/config.exs
  clients/speech/lib/google_api/speech/v1/api/operations.ex
  clients/speech/lib/google_api/speech/v1/api/projects.ex
  clients/speech/lib/google_api/speech/v1/model/recognition_config.ex
  clients/speech/lib/google_api/speech/v1/model/recognition_metadata.ex
  clients/speech/mix.exs
Labels: :rotating_light:, cla: yes
