Repository googleapis/elixir-google-api, pull requests merged in 2021-12, with the labels that each got.

#8752 Regenerate Chat client
  clients/chat/lib/google_api/chat/v1/api/dms.ex
  clients/chat/lib/google_api/chat/v1/api/rooms.ex
  clients/chat/lib/google_api/chat/v1/api/spaces.ex
  clients/chat/lib/google_api/chat/v1/metadata.ex
  clients/chat/lib/google_api/chat/v1/model/membership.ex
  clients/chat/lib/google_api/chat/v1/model/message.ex
  clients/chat/lib/google_api/chat/v1/model/space.ex
  clients/chat/lib/google_api/chat/v1/model/thread.ex
  clients/chat/mix.exs
  clients/chat/synth.metadata
Labels: cla: yes, automerge

#8753 Regenerate CloudSearch client
  clients/cloud_search/lib/google_api/cloud_search/v1/api/v1.ex
  clients/cloud_search/lib/google_api/cloud_search/v1/metadata.ex
  clients/cloud_search/mix.exs
  clients/cloud_search/synth.metadata
Labels: cla: yes, automerge

#8754 Regenerate Content client
  clients/content/lib/google_api/content/v2/metadata.ex
  clients/content/lib/google_api/content/v21/api/liasettings.ex
  clients/content/lib/google_api/content/v21/metadata.ex
  clients/content/lib/google_api/content/v21/model/account.ex
  clients/content/lib/google_api/content/v21/model/account_google_my_business_link.ex
  clients/content/lib/google_api/content/v21/model/gmb_accounts.ex
  clients/content/lib/google_api/content/v21/model/gmb_accounts_gmb_account.ex
  clients/content/lib/google_api/content/v21/model/liasettings_custom_batch_request_entry.ex
  clients/content/lib/google_api/content/v21/model/liasettings_custom_batch_response_entry.ex
  clients/content/lib/google_api/content/v21/model/liasettings_get_accessible_gmb_accounts_response.ex
  clients/content/lib/google_api/content/v21/model/order_tracking_signal_line_item_details.ex
  clients/content/lib/google_api/content/v21/model/order_tracking_signal_shipment_line_item_mapping.ex
  clients/content/lib/google_api/content/v21/model/pos_inventory.ex
  clients/content/lib/google_api/content/v21/model/pos_inventory_request.ex
  clients/content/lib/google_api/content/v21/model/pos_inventory_response.ex
  clients/content/lib/google_api/content/v21/model/pos_sale.ex
  clients/content/lib/google_api/content/v21/model/pos_sale_request.ex
  clients/content/lib/google_api/content/v21/model/pos_sale_response.ex
  clients/content/mix.exs
  clients/content/synth.metadata
Labels: cla: yes, automerge

#8757 Regenerate AndroidManagement client
  clients/android_management/lib/google_api/android_management/v1/metadata.ex
  clients/android_management/lib/google_api/android_management/v1/model/command.ex
  clients/android_management/mix.exs
  clients/android_management/synth.metadata
Labels: cla: yes, automerge

#8758 Regenerate Testing client
  clients/testing/lib/google_api/testing/v1/metadata.ex
  clients/testing/lib/google_api/testing/v1/model/android_instrumentation_test.ex
  clients/testing/mix.exs
  clients/testing/synth.metadata
Labels: cla: yes, automerge

#8760 Regenerate CloudAsset client
  clients/cloud_asset/README.md
  clients/cloud_asset/lib/google_api/cloud_asset/v1/metadata.ex
  clients/cloud_asset/lib/google_api/cloud_asset/v1/model/google_identity_accesscontextmanager_v1_access_policy.ex
  clients/cloud_asset/lib/google_api/cloud_asset/v1/model/iam_policy_analysis_query.ex
  clients/cloud_asset/mix.exs
  clients/cloud_asset/synth.metadata
Labels: cla: yes, automerge

#8761 Regenerate Composer client
  clients/composer/README.md
  clients/composer/lib/google_api/composer/v1/metadata.ex
  clients/composer/lib/google_api/composer/v1/model/environment_config.ex
  clients/composer/lib/google_api/composer/v1/model/maintenance_window.ex
  clients/composer/lib/google_api/composer/v1beta1/metadata.ex
  clients/composer/lib/google_api/composer/v1beta1/model/environment_config.ex
  clients/composer/mix.exs
  clients/composer/synth.metadata
Labels: cla: yes, automerge

#8762 Regenerate Dialogflow client
  clients/dialogflow/README.md
  clients/dialogflow/lib/google_api/dialogflow/v2/metadata.ex
  clients/dialogflow/lib/google_api/dialogflow/v2/model/google_cloud_dialogflow_cx_v3_response_message.ex
  clients/dialogflow/lib/google_api/dialogflow/v2/model/google_cloud_dialogflow_cx_v3_response_message_telephony_transfer_call.ex
  clients/dialogflow/lib/google_api/dialogflow/v2/model/google_cloud_dialogflow_cx_v3beta1_response_message.ex
  clients/dialogflow/lib/google_api/dialogflow/v2/model/google_cloud_dialogflow_cx_v3beta1_response_message_telephony_transfer_call.ex
  clients/dialogflow/mix.exs
  clients/dialogflow/synth.metadata
Labels: cla: yes, automerge

#8763 Regenerate Monitoring client
  clients/monitoring/lib/google_api/monitoring/v3/metadata.ex
  clients/monitoring/lib/google_api/monitoring/v3/model/time_interval.ex
  clients/monitoring/mix.exs
  clients/monitoring/synth.metadata
Labels: cla: yes, automerge

#8765 Regenerate StorageTransfer client
  clients/storage_transfer/lib/google_api/storage_transfer/v1/api/google_service_accounts.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/api/projects.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/api/transfer_jobs.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/metadata.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/agent_pool.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/bandwidth_limit.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/run_transfer_job_request.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/transfer_job.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/transfer_manifest.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/transfer_operation.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/update_transfer_job_request.ex
  clients/storage_transfer/mix.exs
  clients/storage_transfer/synth.metadata
Labels: cla: yes, automerge

#8764 Regenerate Storage client
  clients/storage/lib/google_api/storage/v1/metadata.ex
  clients/storage/lib/google_api/storage/v1/model/bucket_iam_configuration.ex
  clients/storage/mix.exs
  clients/storage/synth.metadata
Labels: cla: yes, automerge

#8766 Regenerate TextToSpeech client
  clients/text_to_speech/lib/google_api/text_to_speech/v1/api/voices.ex
  clients/text_to_speech/lib/google_api/text_to_speech/v1/metadata.ex
  clients/text_to_speech/lib/google_api/text_to_speech/v1beta1/api/voices.ex
  clients/text_to_speech/lib/google_api/text_to_speech/v1beta1/metadata.ex
  clients/text_to_speech/mix.exs
  clients/text_to_speech/synth.metadata
Labels: cla: yes, automerge

#8767 Regenerate BigQuery client
  clients/big_query/README.md
  clients/big_query/lib/google_api/big_query/v2/api/tables.ex
  clients/big_query/lib/google_api/big_query/v2/metadata.ex
  clients/big_query/lib/google_api/big_query/v2/model/destination_table_properties.ex
  clients/big_query/mix.exs
  clients/big_query/synth.metadata
Labels: cla: yes, automerge

#8768 Regenerate BigQueryConnection client
  clients/big_query_connection/lib/google_api/big_query_connection/v1beta1/metadata.ex
  clients/big_query_connection/lib/google_api/big_query_connection/v1beta1/model/get_policy_options.ex
  clients/big_query_connection/mix.exs
  clients/big_query_connection/synth.metadata
Labels: cla: yes, automerge

#8771 Regenerate BigQueryDataTransfer client
  clients/big_query_data_transfer/lib/google_api/big_query_data_transfer/v1/metadata.ex
  clients/big_query_data_transfer/lib/google_api/big_query_data_transfer/v1/model/transfer_config.ex
  clients/big_query_data_transfer/mix.exs
  clients/big_query_data_transfer/synth.metadata
Labels: cla: yes, automerge

#8773 Regenerate CloudKMS client
  clients/cloud_kms/README.md
  clients/cloud_kms/lib/google_api/cloud_kms/v1/api/projects.ex
  clients/cloud_kms/lib/google_api/cloud_kms/v1/metadata.ex
  clients/cloud_kms/lib/google_api/cloud_kms/v1/model/asymmetric_sign_request.ex
  clients/cloud_kms/mix.exs
  clients/cloud_kms/synth.metadata
Labels: cla: yes, automerge

#8774 Regenerate CloudSearch client
  clients/cloud_search/lib/google_api/cloud_search/v1/metadata.ex
  clients/cloud_search/lib/google_api/cloud_search/v1/model/customer_session_stats.ex
  clients/cloud_search/lib/google_api/cloud_search/v1/model/search_application_session_stats.ex
  clients/cloud_search/mix.exs
  clients/cloud_search/synth.metadata
Labels: cla: yes, automerge

#8775 Regenerate Spanner client
  clients/spanner/lib/google_api/spanner/v1/metadata.ex
  clients/spanner/lib/google_api/spanner/v1/model/get_policy_options.ex
  clients/spanner/mix.exs
  clients/spanner/synth.metadata
Labels: cla: yes, automerge

#8776 Regenerate CloudBuild client
  clients/cloud_build/README.md
  clients/cloud_build/lib/google_api/cloud_build/v1/metadata.ex
  clients/cloud_build/lib/google_api/cloud_build/v1/model/create_bitbucket_server_config_operation_metadata.ex
  clients/cloud_build/lib/google_api/cloud_build/v1/model/delete_bitbucket_server_config_operation_metadata.ex
  clients/cloud_build/lib/google_api/cloud_build/v1/model/update_bitbucket_server_config_operation_metadata.ex
  clients/cloud_build/lib/google_api/cloud_build/v1/model/worker_pool.ex
  clients/cloud_build/mix.exs
  clients/cloud_build/synth.metadata
Labels: automerge

#8777 Regenerate CloudFunctions client
  clients/cloud_functions/lib/google_api/cloud_functions/v1/api/projects.ex
  clients/cloud_functions/lib/google_api/cloud_functions/v1/metadata.ex
  clients/cloud_functions/mix.exs
  clients/cloud_functions/synth.metadata
Labels: automerge

#8779 Regenerate DisplayVideo client
  clients/display_video/README.md
  clients/display_video/lib/google_api/display_video/v1/api/advertisers.ex
  clients/display_video/lib/google_api/display_video/v1/metadata.ex
  clients/display_video/lib/google_api/display_video/v1/model/assigned_targeting_option.ex
  clients/display_video/lib/google_api/display_video/v1/model/audio_content_type_assigned_targeting_option_details.ex
  clients/display_video/lib/google_api/display_video/v1/model/audio_content_type_targeting_option_details.ex
  clients/display_video/lib/google_api/display_video/v1/model/targeting_option.ex
  clients/display_video/mix.exs
  clients/display_video/synth.metadata
Labels: automerge

#8780 Regenerate AssuredWorkloads client
  clients/assured_workloads/README.md
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/api/organizations.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/metadata.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/model/google_cloud_assuredworkloads_v1_workload.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/model/google_cloud_assuredworkloads_v1_workload_saa_enrollment_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/model/google_cloud_assuredworkloads_v1beta1_analyze_workload_move_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/model/google_cloud_assuredworkloads_v1beta1_workload.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/model/google_cloud_assuredworkloads_v1beta1_workload_saa_enrollment_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/model/google_cloud_assuredworkloads_versioning_v1main_workload.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1beta1/model/google_cloud_assuredworkloads_versioning_v1main_workload_saa_enrollment_response.ex
  clients/assured_workloads/mix.exs
  clients/assured_workloads/synth.metadata
Labels: automerge

#8781 Regenerate DLP client
  clients/dlp/README.md
  clients/dlp/lib/google_api/dlp/v2/metadata.ex
  clients/dlp/lib/google_api/dlp/v2/model/google_privacy_dlp_v2_big_query_options.ex
  clients/dlp/mix.exs
  clients/dlp/synth.metadata
Labels: automerge

#8782 Regenerate DataCatalog client
  clients/data_catalog/lib/google_api/data_catalog/v1beta1/api/entries.ex
  clients/data_catalog/lib/google_api/data_catalog/v1beta1/metadata.ex
  clients/data_catalog/lib/google_api/data_catalog/v1beta1/model/get_policy_options.ex
  clients/data_catalog/lib/google_api/data_catalog/v1beta1/model/google_cloud_datacatalog_v1beta1_search_catalog_request.ex
  clients/data_catalog/mix.exs
  clients/data_catalog/synth.metadata
Labels: automerge

#8783 Regenerate Dialogflow client
  clients/dialogflow/lib/google_api/dialogflow/v2/metadata.ex
  clients/dialogflow/lib/google_api/dialogflow/v2/model/google_cloud_dialogflow_v2_speech_to_text_config.ex
  clients/dialogflow/mix.exs
  clients/dialogflow/synth.metadata
Labels: automerge

#8784 Regenerate StorageTransfer client
  clients/storage_transfer/lib/google_api/storage_transfer/v1/metadata.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/object_conditions.ex
  clients/storage_transfer/mix.exs
  clients/storage_transfer/synth.metadata
Labels: automerge

#8786 Regenerate AccessContextManager client
  clients/access_context_manager/README.md
  clients/access_context_manager/lib/google_api/access_context_manager/v1/api/access_policies.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/api/organizations.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/connection.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/metadata.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/access_policy.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/audit_config.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/audit_log_config.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/binding.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/get_iam_policy_request.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/get_policy_options.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/policy.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/set_iam_policy_request.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/test_iam_permissions_request.ex
  clients/access_context_manager/lib/google_api/access_context_manager/v1/model/test_iam_permissions_response.ex
  clients/access_context_manager/mix.exs
  clients/access_context_manager/synth.metadata
Labels: automerge

#8787 Regenerate Admin client
  clients/admin/README.md
  clients/admin/lib/google_api/admin/datatransfer_v1/metadata.ex
  clients/admin/lib/google_api/admin/directory_v1/metadata.ex
  clients/admin/lib/google_api/admin/directory_v1/model/chrome_os_device.ex
  clients/admin/lib/google_api/admin/directory_v1/model/user_language.ex
  clients/admin/lib/google_api/admin/reports_v1/api/entity_usage_reports.ex
  clients/admin/lib/google_api/admin/reports_v1/metadata.ex
  clients/admin/mix.exs
  clients/admin/synth.metadata
Labels: automerge

#8789 Regenerate CloudIdentity client
  clients/cloud_identity/README.md
  clients/cloud_identity/lib/google_api/cloud_identity/v1/api/groups.ex
  clients/cloud_identity/lib/google_api/cloud_identity/v1/metadata.ex
  clients/cloud_identity/lib/google_api/cloud_identity/v1/model/member_restriction.ex
  clients/cloud_identity/lib/google_api/cloud_identity/v1/model/membership_role.ex
  clients/cloud_identity/lib/google_api/cloud_identity/v1/model/membership_role_restriction_evaluation.ex
  clients/cloud_identity/lib/google_api/cloud_identity/v1/model/restriction_evaluation.ex
  clients/cloud_identity/lib/google_api/cloud_identity/v1/model/restriction_evaluations.ex
  clients/cloud_identity/lib/google_api/cloud_identity/v1/model/security_settings.ex
  clients/cloud_identity/mix.exs
  clients/cloud_identity/synth.metadata
Labels: automerge

#8790 Regenerate CloudTasks client
  clients/cloud_tasks/lib/google_api/cloud_tasks/v2/metadata.ex
  clients/cloud_tasks/lib/google_api/cloud_tasks/v2/model/get_policy_options.ex
  clients/cloud_tasks/lib/google_api/cloud_tasks/v2/model/http_request.ex
  clients/cloud_tasks/lib/google_api/cloud_tasks/v2beta2/metadata.ex
  clients/cloud_tasks/lib/google_api/cloud_tasks/v2beta2/model/get_policy_options.ex
  clients/cloud_tasks/mix.exs
  clients/cloud_tasks/synth.metadata
Labels: automerge

#8791 Regenerate DocumentAI client
  clients/document_ai/README.md
  clients/document_ai/lib/google_api/document_ai/v1beta2/metadata.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta1_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta1_document_revision.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta2_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta2_document_revision.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/metadata.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta1_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta1_document_revision.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta2_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta2_document_revision.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_document_revision.ex
  clients/document_ai/mix.exs
  clients/document_ai/synth.metadata
Labels: automerge

#8792 Regenerate IAMCredentials client
  clients/iam_credentials/lib/google_api/iam_credentials/v1/connection.ex
  clients/iam_credentials/lib/google_api/iam_credentials/v1/metadata.ex
  clients/iam_credentials/lib/google_api/iam_credentials/v1/model/generate_access_token_request.ex
  clients/iam_credentials/mix.exs
  clients/iam_credentials/synth.metadata
Labels: automerge

#8793 Regenerate Logging client
  clients/logging/lib/google_api/logging/v2/api/billing_accounts.ex
  clients/logging/lib/google_api/logging/v2/api/folders.ex
  clients/logging/lib/google_api/logging/v2/api/organizations.ex
  clients/logging/lib/google_api/logging/v2/api/projects.ex
  clients/logging/lib/google_api/logging/v2/api/v2.ex
  clients/logging/lib/google_api/logging/v2/metadata.ex
  clients/logging/lib/google_api/logging/v2/model/cmek_settings.ex
  clients/logging/mix.exs
  clients/logging/synth.metadata
Labels: automerge

#8794 Regenerate OSLogin client
  clients/os_login/README.md
  clients/os_login/lib/google_api/os_login/v1/api/users.ex
  clients/os_login/lib/google_api/os_login/v1/metadata.ex
  clients/os_login/lib/google_api/os_login/v1alpha/metadata.ex
  clients/os_login/mix.exs
  clients/os_login/synth.metadata
Labels: automerge

#8795 Regenerate PubSub client
  clients/pub_sub/README.md
  clients/pub_sub/lib/google_api/pub_sub/v1/metadata.ex
  clients/pub_sub/lib/google_api/pub_sub/v1/model/subscription.ex
  clients/pub_sub/mix.exs
  clients/pub_sub/synth.metadata
Labels: automerge

#8797 Regenerate Recommender client
  clients/recommender/lib/google_api/recommender/v1/metadata.ex
  clients/recommender/lib/google_api/recommender/v1beta1/api/organizations.ex
  clients/recommender/lib/google_api/recommender/v1beta1/api/projects.ex
  clients/recommender/lib/google_api/recommender/v1beta1/metadata.ex
  clients/recommender/mix.exs
  clients/recommender/synth.metadata
Labels: automerge

#8796 Regenerate RecommendationEngine client
  clients/recommendation_engine/lib/google_api/recommendation_engine/v1beta1/api/projects.ex
  clients/recommendation_engine/lib/google_api/recommendation_engine/v1beta1/metadata.ex
  clients/recommendation_engine/mix.exs
  clients/recommendation_engine/synth.metadata
Labels: automerge

#8799 Regenerate Speech client
  clients/speech/lib/google_api/speech/v1/api/projects.ex
  clients/speech/lib/google_api/speech/v1/metadata.ex
  clients/speech/lib/google_api/speech/v1/model/phrase.ex
  clients/speech/mix.exs
  clients/speech/synth.metadata
Labels: automerge

#8800 Regenerate WebSecurityScanner client
  clients/web_security_scanner/README.md
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1/connection.ex
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1/metadata.ex
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1/model/finding.ex
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1/model/xxe.ex
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1alpha/connection.ex
  clients/web_security_scanner/lib/google_api/web_security_scanner/v1alpha/metadata.ex
  clients/web_security_scanner/mix.exs
  clients/web_security_scanner/synth.metadata
Labels: automerge

#8802 Regenerate APIGateway client
  clients/api_gateway/README.md
  clients/api_gateway/lib/google_api/api_gateway/v1/api/projects.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/connection.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/metadata.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_api.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_api_config.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_api_config_file.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_api_config_grpc_service_definition.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_api_config_open_api_document.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_audit_config.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_audit_log_config.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_binding.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_cancel_operation_request.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_expr.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_gateway.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_list_api_configs_response.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_list_apis_response.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_list_gateways_response.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_list_locations_response.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_list_operations_response.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_location.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_operation.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_operation_metadata.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_operation_metadata_diagnostic.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_policy.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_set_iam_policy_request.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_status.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_test_iam_permissions_request.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/apigateway_test_iam_permissions_response.ex
  clients/api_gateway/lib/google_api/api_gateway/v1/model/empty.ex
  clients/api_gateway/mix.exs
  clients/api_gateway/synth.metadata
Labels: automerge

#8803 Regenerate APIKeys client
  clients/api_keys/.gitignore
  clients/api_keys/LICENSE
  clients/api_keys/README.md
  clients/api_keys/config/config.exs
  clients/api_keys/lib/google_api/api_keys/v2/api/keys.ex
  clients/api_keys/lib/google_api/api_keys/v2/api/operations.ex
  clients/api_keys/lib/google_api/api_keys/v2/api/projects.ex
  clients/api_keys/lib/google_api/api_keys/v2/connection.ex
  clients/api_keys/lib/google_api/api_keys/v2/metadata.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/operation.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/status.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_android_application.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_android_key_restrictions.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_api_target.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_browser_key_restrictions.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_clone_key_request.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_get_key_string_response.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_ios_key_restrictions.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_key.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_list_keys_response.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_lookup_key_response.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_restrictions.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_server_key_restrictions.ex
  clients/api_keys/lib/google_api/api_keys/v2/model/v2_undelete_key_request.ex
  clients/api_keys/mix.exs
  clients/api_keys/synth.metadata
  clients/api_keys/test/test_helper.exs
Labels: automerge

#8805 Regenerate AdSense client
  clients/ad_sense/README.md
  clients/ad_sense/lib/google_api/ad_sense/v2/api/accounts.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/connection.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/metadata.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/account.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/ad_client.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/ad_client_ad_code.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/ad_unit.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/ad_unit_ad_code.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/alert.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/cell.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/content_ads_settings.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/custom_channel.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/date.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/header.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/http_body.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_accounts_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_ad_clients_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_ad_units_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_alerts_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_child_accounts_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_custom_channels_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_linked_ad_units_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_linked_custom_channels_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_payments_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_saved_reports_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_sites_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/list_url_channels_response.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/payment.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/report_result.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/row.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/saved_report.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/site.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/time_zone.ex
  clients/ad_sense/lib/google_api/ad_sense/v2/model/url_channel.ex
  clients/ad_sense/mix.exs
  clients/ad_sense/synth.metadata
Labels: automerge

#8806 Regenerate AnalyticsData client
  clients/analytics_data/README.md
  clients/analytics_data/lib/google_api/analytics_data/v1beta/api/properties.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/connection.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/metadata.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/active_metric_restriction.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/batch_run_pivot_reports_request.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/batch_run_pivot_reports_response.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/batch_run_reports_request.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/batch_run_reports_response.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/between_filter.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/case_expression.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/check_compatibility_request.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/check_compatibility_response.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/cohort.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/cohort_report_settings.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/cohort_spec.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/cohorts_range.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/concatenate_expression.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/date_range.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/dimension.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/dimension_compatibility.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/dimension_expression.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/dimension_header.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/dimension_metadata.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/dimension_order_by.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/dimension_value.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/filter.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/filter_expression.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/filter_expression_list.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/in_list_filter.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/metadata.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/metric.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/metric_compatibility.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/metric_header.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/metric_metadata.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/metric_order_by.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/metric_value.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/minute_range.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/numeric_filter.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/numeric_value.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/order_by.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/pivot.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/pivot_dimension_header.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/pivot_header.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/pivot_order_by.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/pivot_selection.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/property_quota.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/quota_status.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/response_meta_data.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/row.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/run_pivot_report_request.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/run_pivot_report_response.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/run_realtime_report_request.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/run_realtime_report_response.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/run_report_request.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/run_report_response.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/schema_restriction_response.ex
  clients/analytics_data/lib/google_api/analytics_data/v1beta/model/string_filter.ex
  clients/analytics_data/mix.exs
  clients/analytics_data/synth.metadata
Labels: automerge

#8807 Regenerate Apigee client
  clients/apigee/README.md
  clients/apigee/lib/google_api/apigee/v1/api/organizations.ex
  clients/apigee/lib/google_api/apigee/v1/metadata.ex
  clients/apigee/lib/google_api/apigee/v1/model/google_cloud_apigee_v1_adjust_developer_balance_request.ex
  clients/apigee/mix.exs
  clients/apigee/synth.metadata
Labels: automerge

#8811 Regenerate BareMetalSolution client
  clients/bare_metal_solution/.gitignore
  clients/bare_metal_solution/LICENSE
  clients/bare_metal_solution/README.md
  clients/bare_metal_solution/config/config.exs
  clients/bare_metal_solution/lib/google_api/bare_metal_solution/v1/api/projects.ex
  clients/bare_metal_solution/lib/google_api/bare_metal_solution/v1/connection.ex
  clients/bare_metal_solution/lib/google_api/bare_metal_solution/v1/metadata.ex
  clients/bare_metal_solution/lib/google_api/bare_metal_solution/v1/model/reset_instance_request.ex
  clients/bare_metal_solution/lib/google_api/bare_metal_solution/v1/model/reset_instance_response.ex
  clients/bare_metal_solution/mix.exs
  clients/bare_metal_solution/synth.metadata
  clients/bare_metal_solution/test/test_helper.exs
Labels: automerge

#8809 Regenerate AssuredWorkloads client
  clients/assured_workloads/README.md
  clients/assured_workloads/lib/google_api/assured_workloads/v1/api/organizations.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/connection.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/metadata.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1_create_workload_operation_metadata.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1_list_workloads_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1_workload.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1_workload_kms_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1_workload_resource_info.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1_workload_resource_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1_workload_saa_enrollment_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_create_workload_operation_metadata.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_cjis_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_fedramp_high_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_fedramp_moderate_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_i_l4_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_kms_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_resource_info.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_resource_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_v1beta1_workload_saa_enrollment_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_create_workload_operation_metadata.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_cjis_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_fedramp_high_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_fedramp_moderate_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_i_l4_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_kms_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_resource_info.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_resource_settings.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_cloud_assuredworkloads_versioning_v1main_workload_saa_enrollment_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_longrunning_list_operations_response.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_longrunning_operation.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_protobuf_empty.ex
  clients/assured_workloads/lib/google_api/assured_workloads/v1/model/google_rpc_status.ex
  clients/assured_workloads/mix.exs
  clients/assured_workloads/synth.metadata
Labels: automerge

#8815 Regenerate ChromePolicy client
  clients/chrome_policy/.gitignore
  clients/chrome_policy/LICENSE
  clients/chrome_policy/README.md
  clients/chrome_policy/config/config.exs
  clients/chrome_policy/lib/google_api/chrome_policy/v1/api/customers.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/api/media.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/connection.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/metadata.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/chrome_cros_dpanel_autosettings_proto_policy_api_lifecycle.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_additional_target_key_name.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_batch_inherit_org_unit_policies_request.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_batch_modify_org_unit_policies_request.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_inherit_org_unit_policy_request.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_list_policy_schemas_response.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_modify_org_unit_policy_request.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_policy_schema.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_policy_schema_field_dependencies.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_policy_schema_field_description.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_policy_schema_field_known_value_description.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_policy_schema_notice_description.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_policy_target_key.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_policy_value.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_resolve_request.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_resolve_response.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_resolved_policy.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_upload_policy_file_request.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_chrome_policy_v1_upload_policy_file_response.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_protobuf_empty.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/google_type_date.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/proto2_descriptor_proto.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/proto2_enum_descriptor_proto.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/proto2_enum_value_descriptor_proto.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/proto2_field_descriptor_proto.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/proto2_file_descriptor_proto.ex
  clients/chrome_policy/lib/google_api/chrome_policy/v1/model/proto2_oneof_descriptor_proto.ex
  clients/chrome_policy/mix.exs
  clients/chrome_policy/synth.metadata
  clients/chrome_policy/test/test_helper.exs
Labels: automerge

#8814 Regenerate ChromeManagement client
  clients/chrome_management/.gitignore
  clients/chrome_management/LICENSE
  clients/chrome_management/README.md
  clients/chrome_management/config/config.exs
  clients/chrome_management/lib/google_api/chrome_management/v1/api/customers.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/connection.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/metadata.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_android_app_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_android_app_permission.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_app_details.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_battery_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_battery_sample_report.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_battery_status_report.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_browser_version.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_chrome_app_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_chrome_app_permission.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_chrome_app_request.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_chrome_app_site_access.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_count_chrome_app_requests_response.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_count_chrome_versions_response.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_count_installed_apps_response.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_cpu_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_cpu_status_report.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_cpu_temperature_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_device.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_disk_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_display_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_find_installed_app_devices_response.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_graphics_adapter_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_graphics_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_graphics_status_report.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_installed_app.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_list_telemetry_devices_response.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_memory_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_memory_status_report.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_network_status_report.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_os_update_status.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_storage_info.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_storage_info_disk_volume.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_storage_status_report.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_chrome_management_v1_telemetry_device.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_rpc_status.ex
  clients/chrome_management/lib/google_api/chrome_management/v1/model/google_type_date.ex
  clients/chrome_management/mix.exs
  clients/chrome_management/synth.metadata
  clients/chrome_management/test/test_helper.exs
Labels: automerge

#8818 Regenerate CloudDeploy client
  clients/cloud_deploy/.gitignore
  clients/cloud_deploy/LICENSE
  clients/cloud_deploy/README.md
  clients/cloud_deploy/config/config.exs
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/api/projects.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/connection.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/metadata.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/approve_rollout_request.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/approve_rollout_response.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/audit_config.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/audit_log_config.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/binding.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/build_artifact.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/cancel_operation_request.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/config.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/date.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/default_pool.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/delivery_pipeline.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/empty.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/execution_config.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/expr.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/gke_cluster.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/list_delivery_pipelines_response.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/list_locations_response.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/list_operations_response.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/list_releases_response.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/list_rollouts_response.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/list_targets_response.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/location.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/operation.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/operation_metadata.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/pipeline_condition.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/pipeline_ready_condition.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/policy.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/private_pool.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/release.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/rollout.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/serial_pipeline.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/set_iam_policy_request.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/skaffold_version.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/stage.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/status.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/target.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/target_artifact.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/target_render.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/targets_present_condition.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/test_iam_permissions_request.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/test_iam_permissions_response.ex
  clients/cloud_deploy/mix.exs
  clients/cloud_deploy/synth.metadata
  clients/cloud_deploy/test/test_helper.exs
Labels: automerge

#8813 Regenerate Chat client
  clients/chat/README.md
  clients/chat/lib/google_api/chat/v1/metadata.ex
  clients/chat/lib/google_api/chat/v1/model/matched_url.ex
  clients/chat/lib/google_api/chat/v1/model/message.ex
  clients/chat/mix.exs
  clients/chat/synth.metadata
Labels: automerge

#8820 Regenerate CloudSupport client
  clients/cloud_support/.gitignore
  clients/cloud_support/LICENSE
  clients/cloud_support/README.md
  clients/cloud_support/config/config.exs
  clients/cloud_support/lib/google_api/cloud_support/v2beta/api/attachments.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/api/case_classifications.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/api/cases.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/api/media.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/connection.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/metadata.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/actor.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/attachment.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/blobstore2_info.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/case.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/case_classification.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/close_case_request.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/comment.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/composite_media.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/content_type_info.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/create_attachment_request.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/diff_checksums_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/diff_download_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/diff_upload_request.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/diff_upload_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/diff_version_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/download_parameters.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/escalate_case_request.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/escalation.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/list_attachments_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/list_cases_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/list_comments_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/media.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/object_id.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/search_case_classifications_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/search_cases_response.ex
  clients/cloud_support/lib/google_api/cloud_support/v2beta/model/workflow_operation_metadata.ex
  clients/cloud_support/mix.exs
  clients/cloud_support/synth.metadata
  clients/cloud_support/test/test_helper.exs
Labels: automerge

#8827 Regenerate DataPipelines client
  clients/data_pipelines/.gitignore
  clients/data_pipelines/LICENSE
  clients/data_pipelines/README.md
  clients/data_pipelines/config/config.exs
  clients/data_pipelines/lib/google_api/data_pipelines/v1/api/projects.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/connection.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/metadata.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_dataflow_job_details.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_flex_template_runtime_environment.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_job.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_launch_flex_template_parameter.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_launch_flex_template_request.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_launch_template_parameters.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_launch_template_request.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_list_pipelines_response.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_pipeline.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_run_pipeline_request.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_run_pipeline_response.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_runtime_environment.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_schedule_spec.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_sdk_version.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_stop_pipeline_request.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_cloud_datapipelines_v1_workload.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_protobuf_empty.ex
  clients/data_pipelines/lib/google_api/data_pipelines/v1/model/google_rpc_status.ex
  clients/data_pipelines/mix.exs
  clients/data_pipelines/synth.metadata
  clients/data_pipelines/test/test_helper.exs
Labels: automerge

#8834 Regenerate FCMData client
  clients/fcm_data/.gitignore
  clients/fcm_data/LICENSE
  clients/fcm_data/README.md
  clients/fcm_data/config/config.exs
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/api/projects.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/connection.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/metadata.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/model/google_firebase_fcm_data_v1beta1_android_delivery_data.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/model/google_firebase_fcm_data_v1beta1_data.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/model/google_firebase_fcm_data_v1beta1_delivery_performance_percents.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/model/google_firebase_fcm_data_v1beta1_list_android_delivery_data_response.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/model/google_firebase_fcm_data_v1beta1_message_insight_percents.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/model/google_firebase_fcm_data_v1beta1_message_outcome_percents.ex
  clients/fcm_data/lib/google_api/fcm_data/v1beta1/model/google_type_date.ex
  clients/fcm_data/mix.exs
  clients/fcm_data/synth.metadata
  clients/fcm_data/test/test_helper.exs
Labels: automerge

#8836 Regenerate FirebaseDatabase client
  clients/firebase_database/.gitignore
  clients/firebase_database/LICENSE
  clients/firebase_database/README.md
  clients/firebase_database/config/config.exs
  clients/firebase_database/lib/google_api/firebase_database/v1beta/api/projects.ex
  clients/firebase_database/lib/google_api/firebase_database/v1beta/connection.ex
  clients/firebase_database/lib/google_api/firebase_database/v1beta/metadata.ex
  clients/firebase_database/lib/google_api/firebase_database/v1beta/model/database_instance.ex
  clients/firebase_database/lib/google_api/firebase_database/v1beta/model/disable_database_instance_request.ex
  clients/firebase_database/lib/google_api/firebase_database/v1beta/model/list_database_instances_response.ex
  clients/firebase_database/lib/google_api/firebase_database/v1beta/model/reenable_database_instance_request.ex
  clients/firebase_database/mix.exs
  clients/firebase_database/synth.metadata
  clients/firebase_database/test/test_helper.exs
Labels: automerge

#8835 Regenerate FirebaseAppCheck client
  clients/firebase_app_check/.gitignore
  clients/firebase_app_check/LICENSE
  clients/firebase_app_check/README.md
  clients/firebase_app_check/config/config.exs
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/api/jwks.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/api/projects.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/connection.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/metadata.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_app_attest_challenge_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_app_attest_config.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_attestation_token_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_batch_get_app_attest_configs_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_batch_get_device_check_configs_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_batch_get_recaptcha_configs_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_batch_get_recaptcha_enterprise_configs_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_batch_get_safety_net_configs_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_batch_update_services_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_batch_update_services_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_debug_token.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_device_check_config.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_app_attest_assertion_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_app_attest_attestation_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_app_attest_attestation_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_custom_token_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_debug_token_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_device_check_token_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_recaptcha_enterprise_token_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_recaptcha_token_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_exchange_safety_net_token_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_generate_app_attest_challenge_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_list_debug_tokens_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_list_services_response.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_public_jwk.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_public_jwk_set.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_recaptcha_config.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_recaptcha_enterprise_config.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_safety_net_config.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_service.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_firebase_appcheck_v1beta_update_service_request.ex
  clients/firebase_app_check/lib/google_api/firebase_app_check/v1beta/model/google_protobuf_empty.ex
  clients/firebase_app_check/mix.exs
  clients/firebase_app_check/synth.metadata
  clients/firebase_app_check/test/test_helper.exs
Labels: automerge

#8833 Regenerate Eventarc client
  clients/eventarc/README.md
  clients/eventarc/lib/google_api/eventarc/v1/api/projects.ex
  clients/eventarc/lib/google_api/eventarc/v1/connection.ex
  clients/eventarc/lib/google_api/eventarc/v1/metadata.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/audit_config.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/audit_log_config.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/binding.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/cloud_run.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/destination.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/empty.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/event_filter.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/expr.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/gke.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/google_longrunning_cancel_operation_request.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/google_longrunning_list_operations_response.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/google_longrunning_operation.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/google_rpc_status.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/list_locations_response.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/list_triggers_response.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/location.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/operation_metadata.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/policy.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/pubsub.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/set_iam_policy_request.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/test_iam_permissions_request.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/test_iam_permissions_response.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/transport.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/trigger.ex
  clients/eventarc/mix.exs
  clients/eventarc/synth.metadata
Labels: automerge

#8839 Regenerate Genomics client
  clients/genomics/README.md
  clients/genomics/lib/google_api/genomics/v2alpha1/api/pipelines.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/api/projects.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/api/workers.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/connection.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/metadata.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/accelerator.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/action.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/cancel_operation_request.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/check_in_request.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/check_in_response.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/container_killed_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/container_started_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/container_stopped_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/delayed_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/disk.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/disk_status.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/empty.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/existing_disk.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/failed_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/list_operations_response.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/metadata.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/mount.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/network.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/nfs_mount.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/operation.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/persistent_disk.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/pipeline.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/pull_started_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/pull_stopped_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/resources.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/run_pipeline_request.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/run_pipeline_response.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/secret.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/service_account.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/status.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/timestamped_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/unexpected_exit_status_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/virtual_machine.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/volume.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/worker_assigned_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/worker_released_event.ex
  clients/genomics/lib/google_api/genomics/v2alpha1/model/worker_status.ex
  clients/genomics/mix.exs
  clients/genomics/synth.metadata
Labels: automerge

#8842 Regenerate IdeaHub client
  clients/idea_hub/.gitignore
  clients/idea_hub/LICENSE
  clients/idea_hub/README.md
  clients/idea_hub/config/config.exs
  clients/idea_hub/lib/google_api/idea_hub/v1beta/api/platforms.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/connection.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/metadata.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_available_locale.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_idea.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_idea_activity.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_idea_state.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_list_available_locales_response.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_list_ideas_response.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_topic.ex
  clients/idea_hub/lib/google_api/idea_hub/v1beta/model/google_search_ideahub_v1beta_topic_state.ex
  clients/idea_hub/mix.exs
  clients/idea_hub/synth.metadata
  clients/idea_hub/test/test_helper.exs
Labels: automerge

#8844 Regenerate Keep client
  clients/keep/.gitignore
  clients/keep/LICENSE
  clients/keep/README.md
  clients/keep/config/config.exs
  clients/keep/lib/google_api/keep/v1/api/media.ex
  clients/keep/lib/google_api/keep/v1/api/notes.ex
  clients/keep/lib/google_api/keep/v1/connection.ex
  clients/keep/lib/google_api/keep/v1/metadata.ex
  clients/keep/lib/google_api/keep/v1/model/attachment.ex
  clients/keep/lib/google_api/keep/v1/model/batch_create_permissions_request.ex
  clients/keep/lib/google_api/keep/v1/model/batch_create_permissions_response.ex
  clients/keep/lib/google_api/keep/v1/model/batch_delete_permissions_request.ex
  clients/keep/lib/google_api/keep/v1/model/create_permission_request.ex
  clients/keep/lib/google_api/keep/v1/model/empty.ex
  clients/keep/lib/google_api/keep/v1/model/family.ex
  clients/keep/lib/google_api/keep/v1/model/group.ex
  clients/keep/lib/google_api/keep/v1/model/list_content.ex
  clients/keep/lib/google_api/keep/v1/model/list_item.ex
  clients/keep/lib/google_api/keep/v1/model/list_notes_response.ex
  clients/keep/lib/google_api/keep/v1/model/note.ex
  clients/keep/lib/google_api/keep/v1/model/permission.ex
  clients/keep/lib/google_api/keep/v1/model/section.ex
  clients/keep/lib/google_api/keep/v1/model/text_content.ex
  clients/keep/lib/google_api/keep/v1/model/user.ex
  clients/keep/mix.exs
  clients/keep/synth.metadata
  clients/keep/test/test_helper.exs
Labels: automerge

#8850 Regenerate MyBusinessPlaceActions client
  clients/my_business_place_actions/.gitignore
  clients/my_business_place_actions/LICENSE
  clients/my_business_place_actions/README.md
  clients/my_business_place_actions/config/config.exs
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/api/locations.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/api/place_action_type_metadata.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/connection.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/metadata.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/model/empty.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/model/list_place_action_links_response.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/model/list_place_action_type_metadata_response.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/model/place_action_link.ex
  clients/my_business_place_actions/lib/google_api/my_business_place_actions/v1/model/place_action_type_metadata.ex
  clients/my_business_place_actions/mix.exs
  clients/my_business_place_actions/synth.metadata
  clients/my_business_place_actions/test/test_helper.exs
Labels: automerge

#8851 Regenerate MyBusinessVerifications client
  clients/my_business_verifications/.gitignore
  clients/my_business_verifications/LICENSE
  clients/my_business_verifications/README.md
  clients/my_business_verifications/config/config.exs
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/api/locations.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/api/verification_tokens.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/connection.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/metadata.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/address_verification_data.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/complete_verification_request.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/complete_verification_response.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/comply_with_guidelines.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/email_verification_data.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/fetch_verification_options_request.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/fetch_verification_options_response.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/generate_verification_token_request.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/generate_verification_token_response.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/list_verifications_response.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/location.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/postal_address.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/resolve_ownership_conflict.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/service_business_context.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/verification.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/verification_option.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/verification_token.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/verify.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/verify_location_request.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/verify_location_response.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/voice_of_merchant_state.ex
  clients/my_business_verifications/lib/google_api/my_business_verifications/v1/model/wait_for_voice_of_merchant.ex
  clients/my_business_verifications/mix.exs
  clients/my_business_verifications/synth.metadata
  clients/my_business_verifications/test/test_helper.exs
Labels: automerge

#8849 Regenerate MyBusinessNotifications client
  clients/my_business_notifications/.gitignore
  clients/my_business_notifications/LICENSE
  clients/my_business_notifications/README.md
  clients/my_business_notifications/config/config.exs
  clients/my_business_notifications/lib/google_api/my_business_notifications/v1/api/accounts.ex
  clients/my_business_notifications/lib/google_api/my_business_notifications/v1/connection.ex
  clients/my_business_notifications/lib/google_api/my_business_notifications/v1/metadata.ex
  clients/my_business_notifications/lib/google_api/my_business_notifications/v1/model/notification_setting.ex
  clients/my_business_notifications/mix.exs
  clients/my_business_notifications/synth.metadata
  clients/my_business_notifications/test/test_helper.exs
Labels: automerge

#8848 Regenerate MyBusinessLodging client
  clients/my_business_lodging/.gitignore
  clients/my_business_lodging/LICENSE
  clients/my_business_lodging/README.md
  clients/my_business_lodging/config/config.exs
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/api/locations.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/connection.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/metadata.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/accessibility.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/activities.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/business.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/connectivity.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/eco_certification.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/energy_efficiency.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/enhanced_cleaning.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/families.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/food_and_drink.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/get_google_updated_lodging_response.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/guest_unit_features.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/guest_unit_type.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/health_and_safety.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/housekeeping.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/increased_food_safety.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/language_spoken.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/living_area.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/living_area_accessibility.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/living_area_eating.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/living_area_features.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/living_area_layout.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/living_area_sleeping.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/lodging.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/lodging_metadata.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/minimized_contact.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/parking.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/payment_options.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/personal_protection.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/pets.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/physical_distancing.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/policies.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/pools.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/property.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/services.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/sustainability.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/sustainability_certifications.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/sustainable_sourcing.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/time_of_day.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/transportation.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/views_from_unit.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/waste_reduction.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/water_conservation.ex
  clients/my_business_lodging/lib/google_api/my_business_lodging/v1/model/wellness.ex
  clients/my_business_lodging/mix.exs
  clients/my_business_lodging/synth.metadata
  clients/my_business_lodging/test/test_helper.exs
Labels: automerge

#8854 Regenerate NetworkServices client
  clients/network_services/.gitignore
  clients/network_services/LICENSE
  clients/network_services/README.md
  clients/network_services/config/config.exs
  clients/network_services/lib/google_api/network_services/v1/api/projects.ex
  clients/network_services/lib/google_api/network_services/v1/connection.ex
  clients/network_services/lib/google_api/network_services/v1/metadata.ex
  clients/network_services/lib/google_api/network_services/v1/model/audit_config.ex
  clients/network_services/lib/google_api/network_services/v1/model/audit_log_config.ex
  clients/network_services/lib/google_api/network_services/v1/model/binding.ex
  clients/network_services/lib/google_api/network_services/v1/model/cancel_operation_request.ex
  clients/network_services/lib/google_api/network_services/v1/model/empty.ex
  clients/network_services/lib/google_api/network_services/v1/model/endpoint_matcher.ex
  clients/network_services/lib/google_api/network_services/v1/model/endpoint_matcher_metadata_label_matcher.ex
  clients/network_services/lib/google_api/network_services/v1/model/endpoint_matcher_metadata_label_matcher_metadata_labels.ex
  clients/network_services/lib/google_api/network_services/v1/model/endpoint_policy.ex
  clients/network_services/lib/google_api/network_services/v1/model/expr.ex
  clients/network_services/lib/google_api/network_services/v1/model/list_endpoint_policies_response.ex
  clients/network_services/lib/google_api/network_services/v1/model/list_locations_response.ex
  clients/network_services/lib/google_api/network_services/v1/model/list_operations_response.ex
  clients/network_services/lib/google_api/network_services/v1/model/location.ex
  clients/network_services/lib/google_api/network_services/v1/model/operation.ex
  clients/network_services/lib/google_api/network_services/v1/model/operation_metadata.ex
  clients/network_services/lib/google_api/network_services/v1/model/policy.ex
  clients/network_services/lib/google_api/network_services/v1/model/set_iam_policy_request.ex
  clients/network_services/lib/google_api/network_services/v1/model/status.ex
  clients/network_services/lib/google_api/network_services/v1/model/test_iam_permissions_request.ex
  clients/network_services/lib/google_api/network_services/v1/model/test_iam_permissions_response.ex
  clients/network_services/lib/google_api/network_services/v1/model/traffic_port_selector.ex
  clients/network_services/mix.exs
  clients/network_services/synth.metadata
  clients/network_services/test/test_helper.exs
Labels: automerge

#8853 Regenerate NetworkSecurity client
  clients/network_security/.gitignore
  clients/network_security/LICENSE
  clients/network_security/README.md
  clients/network_security/config/config.exs
  clients/network_security/lib/google_api/network_security/v1/api/projects.ex
  clients/network_security/lib/google_api/network_security/v1/connection.ex
  clients/network_security/lib/google_api/network_security/v1/metadata.ex
  clients/network_security/lib/google_api/network_security/v1/model/authorization_policy.ex
  clients/network_security/lib/google_api/network_security/v1/model/cancel_operation_request.ex
  clients/network_security/lib/google_api/network_security/v1/model/certificate_provider_instance.ex
  clients/network_security/lib/google_api/network_security/v1/model/client_tls_policy.ex
  clients/network_security/lib/google_api/network_security/v1/model/destination.ex
  clients/network_security/lib/google_api/network_security/v1/model/empty.ex
  clients/network_security/lib/google_api/network_security/v1/model/expr.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_cloud_networksecurity_v1_certificate_provider.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_cloud_networksecurity_v1_grpc_endpoint.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_iam_v1_audit_config.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_iam_v1_audit_log_config.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_iam_v1_binding.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_iam_v1_policy.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_iam_v1_set_iam_policy_request.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_iam_v1_test_iam_permissions_request.ex
  clients/network_security/lib/google_api/network_security/v1/model/google_iam_v1_test_iam_permissions_response.ex
  clients/network_security/lib/google_api/network_security/v1/model/http_header_match.ex
  clients/network_security/lib/google_api/network_security/v1/model/list_authorization_policies_response.ex
  clients/network_security/lib/google_api/network_security/v1/model/list_client_tls_policies_response.ex
  clients/network_security/lib/google_api/network_security/v1/model/list_locations_response.ex
  clients/network_security/lib/google_api/network_security/v1/model/list_operations_response.ex
  clients/network_security/lib/google_api/network_security/v1/model/list_server_tls_policies_response.ex
  clients/network_security/lib/google_api/network_security/v1/model/location.ex
  clients/network_security/lib/google_api/network_security/v1/model/mtls_policy.ex
  clients/network_security/lib/google_api/network_security/v1/model/operation.ex
  clients/network_security/lib/google_api/network_security/v1/model/operation_metadata.ex
  clients/network_security/lib/google_api/network_security/v1/model/rule.ex
  clients/network_security/lib/google_api/network_security/v1/model/server_tls_policy.ex
  clients/network_security/lib/google_api/network_security/v1/model/source.ex
  clients/network_security/lib/google_api/network_security/v1/model/status.ex
  clients/network_security/lib/google_api/network_security/v1/model/validation_ca.ex
  clients/network_security/mix.exs
  clients/network_security/synth.metadata
  clients/network_security/test/test_helper.exs
Labels: automerge

#8846 Regenerate MyBusinessAccountManagement client
  clients/my_business_account_management/.gitignore
  clients/my_business_account_management/LICENSE
  clients/my_business_account_management/README.md
  clients/my_business_account_management/config/config.exs
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/api/accounts.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/api/locations.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/connection.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/metadata.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/accept_invitation_request.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/account.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/admin.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/decline_invitation_request.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/empty.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/invitation.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/list_account_admins_response.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/list_accounts_response.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/list_invitations_response.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/list_location_admins_response.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/organization_info.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/postal_address.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/target_location.ex
  clients/my_business_account_management/lib/google_api/my_business_account_management/v1/model/transfer_location_request.ex
  clients/my_business_account_management/mix.exs
  clients/my_business_account_management/synth.metadata
  clients/my_business_account_management/test/test_helper.exs
Labels: automerge

#8852 Regenerate NetworkConnectivity client
  clients/network_connectivity/.gitignore
  clients/network_connectivity/LICENSE
  clients/network_connectivity/README.md
  clients/network_connectivity/config/config.exs
  clients/network_connectivity/lib/google_api/network_connectivity/v1/api/projects.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/connection.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/metadata.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/audit_config.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/audit_log_config.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/binding.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/empty.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/expr.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/google_longrunning_cancel_operation_request.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/google_longrunning_list_operations_response.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/google_longrunning_operation.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/google_rpc_status.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/hub.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/linked_interconnect_attachments.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/linked_router_appliance_instances.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/linked_vpn_tunnels.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/list_hubs_response.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/list_locations_response.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/list_spokes_response.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/location.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/location_metadata.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/operation_metadata.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/policy.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/router_appliance_instance.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/routing_vpc.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/set_iam_policy_request.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/spoke.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/test_iam_permissions_request.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/test_iam_permissions_response.ex
  clients/network_connectivity/mix.exs
  clients/network_connectivity/synth.metadata
  clients/network_connectivity/test/test_helper.exs
Labels: automerge

#8862 Regenerate PolicyAnalyzer client
  clients/policy_analyzer/.gitignore
  clients/policy_analyzer/LICENSE
  clients/policy_analyzer/README.md
  clients/policy_analyzer/config/config.exs
  clients/policy_analyzer/lib/google_api/policy_analyzer/v1/api/projects.ex
  clients/policy_analyzer/lib/google_api/policy_analyzer/v1/connection.ex
  clients/policy_analyzer/lib/google_api/policy_analyzer/v1/metadata.ex
  clients/policy_analyzer/lib/google_api/policy_analyzer/v1/model/google_cloud_policyanalyzer_v1_activity.ex
  clients/policy_analyzer/lib/google_api/policy_analyzer/v1/model/google_cloud_policyanalyzer_v1_observation_period.ex
  clients/policy_analyzer/lib/google_api/policy_analyzer/v1/model/google_cloud_policyanalyzer_v1_query_activity_response.ex
  clients/policy_analyzer/mix.exs
  clients/policy_analyzer/synth.metadata
  clients/policy_analyzer/test/test_helper.exs
Labels: automerge

#8863 Regenerate PolicySimulator client
  clients/policy_simulator/.gitignore
  clients/policy_simulator/LICENSE
  clients/policy_simulator/README.md
  clients/policy_simulator/config/config.exs
  clients/policy_simulator/lib/google_api/policy_simulator/v1/api/folders.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/api/operations.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/api/organizations.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/api/projects.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/connection.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/metadata.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_access_state_diff.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_access_tuple.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_binding_explanation.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_binding_explanation_annotated_membership.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_explained_access.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_explained_policy.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_list_replay_results_response.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_replay.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_replay_config.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_replay_diff.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_replay_operation_metadata.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_replay_result.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1_replay_results_summary.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1beta1_replay.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1beta1_replay_config.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1beta1_replay_operation_metadata.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_cloud_policysimulator_v1beta1_replay_results_summary.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_iam_v1_audit_config.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_iam_v1_audit_log_config.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_iam_v1_binding.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_iam_v1_policy.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_longrunning_list_operations_response.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_longrunning_operation.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_rpc_status.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_type_date.ex
  clients/policy_simulator/lib/google_api/policy_simulator/v1/model/google_type_expr.ex
  clients/policy_simulator/mix.exs
  clients/policy_simulator/synth.metadata
  clients/policy_simulator/test/test_helper.exs
Labels: automerge

#8865 Regenerate RecaptchaEnterprise client
  clients/recaptcha_enterprise/.gitignore
  clients/recaptcha_enterprise/LICENSE
  clients/recaptcha_enterprise/README.md
  clients/recaptcha_enterprise/config/config.exs
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/api/projects.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/connection.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/metadata.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_account_defender_assessment.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_android_key_settings.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_annotate_assessment_request.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_annotate_assessment_response.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_assessment.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_challenge_metrics.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_event.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_ios_key_settings.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_key.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_list_keys_response.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_list_related_account_group_memberships_response.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_list_related_account_groups_response.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_metrics.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_migrate_key_request.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_related_account_group.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_related_account_group_membership.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_risk_analysis.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_score_distribution.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_score_metrics.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_search_related_account_group_memberships_request.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_search_related_account_group_memberships_response.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_testing_options.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_token_properties.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_cloud_recaptchaenterprise_v1_web_key_settings.ex
  clients/recaptcha_enterprise/lib/google_api/recaptcha_enterprise/v1/model/google_protobuf_empty.ex
  clients/recaptcha_enterprise/mix.exs
  clients/recaptcha_enterprise/synth.metadata
  clients/recaptcha_enterprise/test/test_helper.exs
Labels: automerge

#8858 Regenerate OSLogin client
  clients/os_login/lib/google_api/os_login/v1alpha/api/users.ex
  clients/os_login/lib/google_api/os_login/v1alpha/metadata.ex
  clients/os_login/synth.metadata
Labels: automerge

#8866 Regenerate ResourceSettings client
  clients/resource_settings/.gitignore
  clients/resource_settings/LICENSE
  clients/resource_settings/README.md
  clients/resource_settings/config/config.exs
  clients/resource_settings/lib/google_api/resource_settings/v1/api/folders.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/api/organizations.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/api/projects.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/connection.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/metadata.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/model/google_cloud_resourcesettings_v1_list_settings_response.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/model/google_cloud_resourcesettings_v1_setting.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/model/google_cloud_resourcesettings_v1_setting_metadata.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/model/google_cloud_resourcesettings_v1_value.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/model/google_cloud_resourcesettings_v1_value_enum_value.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/model/google_cloud_resourcesettings_v1_value_string_map.ex
  clients/resource_settings/lib/google_api/resource_settings/v1/model/google_cloud_resourcesettings_v1_value_string_set.ex
  clients/resource_settings/mix.exs
  clients/resource_settings/synth.metadata
  clients/resource_settings/test/test_helper.exs
Labels: automerge

#8870 Regenerate Transcoder client
  clients/transcoder/.gitignore
  clients/transcoder/LICENSE
  clients/transcoder/README.md
  clients/transcoder/config/config.exs
  clients/transcoder/lib/google_api/transcoder/v1beta1/api/projects.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/connection.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/metadata.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/ad_break.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/aes128_encryption.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/animation.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/animation_end.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/animation_fade.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/animation_static.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/audio.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/audio_atom.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/audio_channel.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/audio_channel_input.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/audio_stream.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/color.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/crop.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/deblock.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/denoise.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/edit_atom.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/elementary_stream.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/empty.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/encryption.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/failure_detail.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/image.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/input.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/job.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/job_config.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/job_template.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/list_job_templates_response.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/list_jobs_response.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/manifest.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/mpeg_common_encryption.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/mux_stream.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/normalized_coordinate.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/origin_uri.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/output.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/overlay.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/pad.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/preprocessing_config.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/progress.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/pubsub_destination.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/sample_aes_encryption.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/segment_settings.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/sprite_sheet.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/text_atom.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/text_input.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/text_stream.ex
  clients/transcoder/lib/google_api/transcoder/v1beta1/model/video_stream.ex
  clients/transcoder/mix.exs
  clients/transcoder/synth.metadata
  clients/transcoder/test/test_helper.exs
Labels: automerge

#8872 Regenerate VersionHistory client
  clients/version_history/.gitignore
  clients/version_history/LICENSE
  clients/version_history/README.md
  clients/version_history/config/config.exs
  clients/version_history/lib/google_api/version_history/v1/api/platforms.ex
  clients/version_history/lib/google_api/version_history/v1/connection.ex
  clients/version_history/lib/google_api/version_history/v1/metadata.ex
  clients/version_history/lib/google_api/version_history/v1/model/channel.ex
  clients/version_history/lib/google_api/version_history/v1/model/interval.ex
  clients/version_history/lib/google_api/version_history/v1/model/list_channels_response.ex
  clients/version_history/lib/google_api/version_history/v1/model/list_platforms_response.ex
  clients/version_history/lib/google_api/version_history/v1/model/list_releases_response.ex
  clients/version_history/lib/google_api/version_history/v1/model/list_versions_response.ex
  clients/version_history/lib/google_api/version_history/v1/model/platform.ex
  clients/version_history/lib/google_api/version_history/v1/model/release.ex
  clients/version_history/lib/google_api/version_history/v1/model/version.ex
  clients/version_history/mix.exs
  clients/version_history/synth.metadata
  clients/version_history/test/test_helper.exs
Labels: automerge

#8873 Regenerate WebRisk client
  clients/web_risk/.gitignore
  clients/web_risk/LICENSE
  clients/web_risk/README.md
  clients/web_risk/config/config.exs
  clients/web_risk/lib/google_api/web_risk/v1/api/hashes.ex
  clients/web_risk/lib/google_api/web_risk/v1/api/projects.ex
  clients/web_risk/lib/google_api/web_risk/v1/api/threat_lists.ex
  clients/web_risk/lib/google_api/web_risk/v1/api/uris.ex
  clients/web_risk/lib/google_api/web_risk/v1/connection.ex
  clients/web_risk/lib/google_api/web_risk/v1/metadata.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_compute_threat_list_diff_response.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_compute_threat_list_diff_response_checksum.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_raw_hashes.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_raw_indices.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_rice_delta_encoding.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_search_hashes_response.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_search_hashes_response_threat_hash.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_search_uris_response.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_search_uris_response_threat_uri.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_submission.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_submit_uri_metadata.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_submit_uri_request.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_threat_entry_additions.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_cloud_webrisk_v1_threat_entry_removals.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_longrunning_cancel_operation_request.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_longrunning_list_operations_response.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_longrunning_operation.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_protobuf_empty.ex
  clients/web_risk/lib/google_api/web_risk/v1/model/google_rpc_status.ex
  clients/web_risk/mix.exs
  clients/web_risk/synth.metadata
  clients/web_risk/test/test_helper.exs
Labels: automerge

#8876 Regenerate DataMigration client
  clients/data_migration/README.md
  clients/data_migration/lib/google_api/data_migration/v1/api/projects.ex
  clients/data_migration/lib/google_api/data_migration/v1/metadata.ex
  clients/data_migration/lib/google_api/data_migration/v1/model/cloud_sql_settings.ex
  clients/data_migration/lib/google_api/data_migration/v1beta1/api/projects.ex
  clients/data_migration/lib/google_api/data_migration/v1beta1/metadata.ex
  clients/data_migration/mix.exs
  clients/data_migration/synth.metadata
Labels: automerge

#8877 Regenerate Eventarc client
  clients/eventarc/lib/google_api/eventarc/v1/metadata.ex
  clients/eventarc/lib/google_api/eventarc/v1/model/destination.ex
  clients/eventarc/lib/google_api/eventarc/v1beta1/metadata.ex
  clients/eventarc/mix.exs
  clients/eventarc/synth.metadata
Labels: automerge

#8878 Regenerate GKEHub client
  clients/gke_hub/README.md
  clients/gke_hub/lib/google_api/gke_hub/v1/metadata.ex
  clients/gke_hub/lib/google_api/gke_hub/v1/model/resource_options.ex
  clients/gke_hub/mix.exs
  clients/gke_hub/synth.metadata
Labels: automerge

#8879 Regenerate Redis client
  clients/redis/README.md
  clients/redis/lib/google_api/redis/v1/metadata.ex
  clients/redis/lib/google_api/redis/v1/model/cluster.ex
  clients/redis/lib/google_api/redis/v1/model/cluster_slots.ex
  clients/redis/lib/google_api/redis/v1/model/endpoint.ex
  clients/redis/lib/google_api/redis/v1/model/private_service_connect.ex
  clients/redis/lib/google_api/redis/v1beta1/metadata.ex
  clients/redis/lib/google_api/redis/v1beta1/model/cluster.ex
  clients/redis/lib/google_api/redis/v1beta1/model/cluster_slots.ex
  clients/redis/lib/google_api/redis/v1beta1/model/endpoint.ex
  clients/redis/lib/google_api/redis/v1beta1/model/private_service_connect.ex
  clients/redis/mix.exs
  clients/redis/synth.metadata
Labels: automerge

#8881 Regenerate VMMigration client
  clients/vm_migration/README.md
  clients/vm_migration/lib/google_api/vm_migration/v1/metadata.ex
  clients/vm_migration/lib/google_api/vm_migration/v1/model/compute_engine_target_defaults.ex
  clients/vm_migration/lib/google_api/vm_migration/v1/model/compute_engine_target_details.ex
  clients/vm_migration/mix.exs
  clients/vm_migration/synth.metadata
Labels: automerge

#8882 Regenerate AnalyticsAdmin client
  clients/analytics_admin/README.md
  clients/analytics_admin/lib/google_api/analytics_admin/v1alpha/metadata.ex
  clients/analytics_admin/lib/google_api/analytics_admin/v1alpha/model/google_analytics_admin_v1alpha_custom_metric.ex
  clients/analytics_admin/mix.exs
  clients/analytics_admin/synth.metadata
Labels: automerge

#8884 Regenerate ContactCenterInsights client
  clients/contact_center_insights/README.md
  clients/contact_center_insights/lib/google_api/contact_center_insights/v1/metadata.ex
  clients/contact_center_insights/lib/google_api/contact_center_insights/v1/model/google_cloud_contactcenterinsights_v1_conversation.ex
  clients/contact_center_insights/mix.exs
  clients/contact_center_insights/synth.metadata
Labels: automerge

#8885 Regenerate Container client
  clients/container/README.md
  clients/container/lib/google_api/container/v1/metadata.ex
  clients/container/lib/google_api/container/v1/model/cluster_update.ex
  clients/container/lib/google_api/container/v1/model/filter.ex
  clients/container/lib/google_api/container/v1/model/maintenance_exclusion_options.ex
  clients/container/lib/google_api/container/v1/model/network_config.ex
  clients/container/lib/google_api/container/v1/model/node_kubelet_config.ex
  clients/container/lib/google_api/container/v1/model/pub_sub.ex
  clients/container/lib/google_api/container/v1/model/security_bulletin_event.ex
  clients/container/lib/google_api/container/v1/model/service_external_i_ps_config.ex
  clients/container/lib/google_api/container/v1/model/time_window.ex
  clients/container/mix.exs
  clients/container/synth.metadata
Labels: automerge

#8887 Regenerate HealthCare client
  clients/health_care/README.md
  clients/health_care/lib/google_api/health_care/v1/api/projects.ex
  clients/health_care/lib/google_api/health_care/v1/metadata.ex
  clients/health_care/lib/google_api/health_care/v1/model/field_metadata.ex
  clients/health_care/lib/google_api/health_care/v1/model/parser_config.ex
  clients/health_care/lib/google_api/health_care/v1/model/validation_config.ex
  clients/health_care/lib/google_api/health_care/v1beta1/api/projects.ex
  clients/health_care/lib/google_api/health_care/v1beta1/metadata.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/crypto_hash_config.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/date_shift_config.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/field_metadata.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/parser_config.ex
  clients/health_care/mix.exs
  clients/health_care/synth.metadata
Labels: automerge

#8888 Regenerate MyBusinessBusinessInformation client
  clients/my_business_business_information/lib/google_api/my_business_business_information/v1/api/locations.ex
  clients/my_business_business_information/lib/google_api/my_business_business_information/v1/metadata.ex
  clients/my_business_business_information/lib/google_api/my_business_business_information/v1/model/location.ex
  clients/my_business_business_information/mix.exs
  clients/my_business_business_information/synth.metadata
Labels: automerge

#8889 Regenerate SQLAdmin client
  clients/sql_admin/lib/google_api/sql_admin/v1/metadata.ex
  clients/sql_admin/lib/google_api/sql_admin/v1/model/database_instance.ex
  clients/sql_admin/lib/google_api/sql_admin/v1/model/ip_configuration.ex
  clients/sql_admin/lib/google_api/sql_admin/v1/model/location_preference.ex
  clients/sql_admin/lib/google_api/sql_admin/v1/model/settings.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/metadata.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/database_instance.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/ip_configuration.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/location_preference.ex
  clients/sql_admin/lib/google_api/sql_admin/v1beta4/model/settings.ex
  clients/sql_admin/synth.metadata
Labels: automerge

#8890 Regenerate ServiceNetworking client
  clients/service_networking/lib/google_api/service_networking/v1/metadata.ex
  clients/service_networking/lib/google_api/service_networking/v1/model/control.ex
  clients/service_networking/mix.exs
  clients/service_networking/synth.metadata
Labels: automerge

#8891 Regenerate StorageTransfer client
  clients/storage_transfer/README.md
  clients/storage_transfer/lib/google_api/storage_transfer/v1/metadata.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/azure_credentials.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/logging_config.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/metadata_options.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/transfer_options.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/transfer_spec.ex
  clients/storage_transfer/mix.exs
  clients/storage_transfer/synth.metadata
Labels: automerge

#8892 Regenerate Admin client
  clients/admin/lib/google_api/admin/datatransfer_v1/metadata.ex
  clients/admin/lib/google_api/admin/directory_v1/api/chromeosdevices.ex
  clients/admin/lib/google_api/admin/directory_v1/api/orgunits.ex
  clients/admin/lib/google_api/admin/directory_v1/metadata.ex
  clients/admin/lib/google_api/admin/directory_v1/model/user_language.ex
  clients/admin/lib/google_api/admin/reports_v1/metadata.ex
  clients/admin/mix.exs
  clients/admin/synth.metadata
Labels: automerge

#8893 Regenerate CloudBilling client
  clients/cloud_billing/lib/google_api/cloud_billing/v1/api/projects.ex
  clients/cloud_billing/lib/google_api/cloud_billing/v1/metadata.ex
  clients/cloud_billing/mix.exs
  clients/cloud_billing/synth.metadata
Labels: automerge

#8894 Regenerate Compute client
  clients/compute/README.md
  clients/compute/lib/google_api/compute/v1/api/disks.ex
  clients/compute/lib/google_api/compute/v1/api/global_public_delegated_prefixes.ex
  clients/compute/lib/google_api/compute/v1/api/public_advertised_prefixes.ex
  clients/compute/lib/google_api/compute/v1/api/public_delegated_prefixes.ex
  clients/compute/lib/google_api/compute/v1/api/region_disks.ex
  clients/compute/lib/google_api/compute/v1/api/region_notification_endpoints.ex
  clients/compute/lib/google_api/compute/v1/api/region_ssl_certificates.ex
  clients/compute/lib/google_api/compute/v1/api/region_target_https_proxies.ex
  clients/compute/lib/google_api/compute/v1/api/service_attachments.ex
  clients/compute/lib/google_api/compute/v1/api/snapshots.ex
  clients/compute/lib/google_api/compute/v1/api/ssl_certificates.ex
  clients/compute/lib/google_api/compute/v1/api/target_grpc_proxies.ex
  clients/compute/lib/google_api/compute/v1/api/target_http_proxies.ex
  clients/compute/lib/google_api/compute/v1/api/target_https_proxies.ex
  clients/compute/lib/google_api/compute/v1/metadata.ex
  clients/compute/lib/google_api/compute/v1/model/access_config.ex
  clients/compute/lib/google_api/compute/v1/model/attached_disk_initialize_params.ex
  clients/compute/lib/google_api/compute/v1/model/instance_properties.ex
  clients/compute/lib/google_api/compute/v1/model/interconnect_attachment.ex
  clients/compute/lib/google_api/compute/v1/model/network_endpoint_group.ex
  clients/compute/lib/google_api/compute/v1/model/network_interface.ex
  clients/compute/lib/google_api/compute/v1/model/service_attachment.ex
  clients/compute/lib/google_api/compute/v1/model/subnetwork.ex
  clients/compute/mix.exs
  clients/compute/synth.metadata
Labels: automerge

#8895 Regenerate Dialogflow client
  clients/dialogflow/README.md
  clients/dialogflow/lib/google_api/dialogflow/v2/metadata.ex
  clients/dialogflow/lib/google_api/dialogflow/v2/model/google_cloud_dialogflow_v2beta1_knowledge_operation_metadata.ex
  clients/dialogflow/lib/google_api/dialogflow/v3/metadata.ex
  clients/dialogflow/lib/google_api/dialogflow/v3/model/google_cloud_dialogflow_v2beta1_knowledge_operation_metadata.ex
  clients/dialogflow/mix.exs
  clients/dialogflow/synth.metadata
Labels: automerge

#8896 Regenerate DocumentAI client
  clients/document_ai/lib/google_api/document_ai/v1/api/projects.ex
  clients/document_ai/lib/google_api/document_ai/v1/metadata.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_batch_process_metadata_individual_process_status.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_processor.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_processor_type.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_processor_version.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1_review_document_request.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1beta1_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1beta1_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1beta1_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1beta2_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1beta2_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1beta2_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1/model/google_cloud_documentai_v1beta3_batch_process_metadata_individual_process_status.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/metadata.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1_batch_process_metadata_individual_process_status.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta1_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta1_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta1_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta2_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta2_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta2_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta2/model/google_cloud_documentai_v1beta3_batch_process_metadata_individual_process_status.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/api/projects.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/metadata.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1_batch_process_metadata_individual_process_status.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta1_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta1_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta1_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta2_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta2_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta2_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_batch_process_metadata_individual_process_status.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_document_entity.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_document_entity_normalized_value.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_document_provenance_parent.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_processor.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_processor_type.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_processor_version.ex
  clients/document_ai/lib/google_api/document_ai/v1beta3/model/google_cloud_documentai_v1beta3_review_document_request.ex
  clients/document_ai/mix.exs
  clients/document_ai/synth.metadata
Labels: automerge

#8897 Regenerate Monitoring client
  clients/monitoring/lib/google_api/monitoring/v3/metadata.ex
  clients/monitoring/lib/google_api/monitoring/v3/model/http_check.ex
  clients/monitoring/lib/google_api/monitoring/v3/model/time_interval.ex
  clients/monitoring/mix.exs
  clients/monitoring/synth.metadata
Labels: automerge

#8898 Regenerate NetworkConnectivity client
  clients/network_connectivity/README.md
  clients/network_connectivity/lib/google_api/network_connectivity/v1/metadata.ex
  clients/network_connectivity/lib/google_api/network_connectivity/v1/model/routing_vpc.ex
  clients/network_connectivity/mix.exs
  clients/network_connectivity/synth.metadata
Labels: automerge

#8900 Regenerate Retail client
  clients/retail/lib/google_api/retail/v2/metadata.ex
  clients/retail/lib/google_api/retail/v2/model/google_cloud_retail_v2_gcs_source.ex
  clients/retail/lib/google_api/retail/v2/model/google_cloud_retail_v2_price_info.ex
  clients/retail/lib/google_api/retail/v2/model/google_cloud_retail_v2_search_request.ex
  clients/retail/lib/google_api/retail/v2/model/google_cloud_retail_v2_set_inventory_request.ex
  clients/retail/mix.exs
  clients/retail/synth.metadata
Labels: automerge

#8901 Regenerate SourceRepo client
  clients/source_repo/lib/google_api/source_repo/v1/api/projects.ex
  clients/source_repo/lib/google_api/source_repo/v1/metadata.ex
  clients/source_repo/mix.exs
  clients/source_repo/synth.metadata
Labels: automerge

#8902 Regenerate Spanner client
  clients/spanner/lib/google_api/spanner/v1/api/projects.ex
  clients/spanner/lib/google_api/spanner/v1/metadata.ex
  clients/spanner/mix.exs
  clients/spanner/synth.metadata
Labels: automerge

#8903 Regenerate StorageTransfer client
  clients/storage_transfer/lib/google_api/storage_transfer/v1/metadata.ex
  clients/storage_transfer/lib/google_api/storage_transfer/v1/model/update_transfer_job_request.ex
  clients/storage_transfer/synth.metadata
Labels: automerge

#8904 Regenerate Apigee client
  clients/apigee/README.md
  clients/apigee/lib/google_api/apigee/v1/metadata.ex
  clients/apigee/lib/google_api/apigee/v1/model/google_cloud_apigee_v1_api_product_ref.ex
  clients/apigee/lib/google_api/apigee/v1/model/google_cloud_apigee_v1_organization_project_mapping.ex
  clients/apigee/mix.exs
  clients/apigee/synth.metadata
Labels: automerge

#8905 Regenerate DNS client
  clients/dns/README.md
  clients/dns/lib/google_api/dns/v1/api/response_policies.ex
  clients/dns/lib/google_api/dns/v1/api/response_policy_rules.ex
  clients/dns/lib/google_api/dns/v1/metadata.ex
  clients/dns/lib/google_api/dns/v1/model/response_policies_list_response.ex
  clients/dns/lib/google_api/dns/v1/model/response_policies_patch_response.ex
  clients/dns/lib/google_api/dns/v1/model/response_policies_update_response.ex
  clients/dns/lib/google_api/dns/v1/model/response_policy.ex
  clients/dns/lib/google_api/dns/v1/model/response_policy_network.ex
  clients/dns/lib/google_api/dns/v1/model/response_policy_rule.ex
  clients/dns/lib/google_api/dns/v1/model/response_policy_rule_local_data.ex
  clients/dns/lib/google_api/dns/v1/model/response_policy_rules_list_response.ex
  clients/dns/lib/google_api/dns/v1/model/response_policy_rules_patch_response.ex
  clients/dns/lib/google_api/dns/v1/model/response_policy_rules_update_response.ex
  clients/dns/mix.exs
  clients/dns/synth.metadata
Labels: automerge

#8906 Regenerate HealthCare client
  clients/health_care/README.md
  clients/health_care/lib/google_api/health_care/v1/api/projects.ex
  clients/health_care/lib/google_api/health_care/v1/metadata.ex
  clients/health_care/lib/google_api/health_care/v1/model/field_metadata.ex
  clients/health_care/lib/google_api/health_care/v1/model/parser_config.ex
  clients/health_care/lib/google_api/health_care/v1/model/validation_config.ex
  clients/health_care/lib/google_api/health_care/v1beta1/api/projects.ex
  clients/health_care/lib/google_api/health_care/v1beta1/metadata.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/crypto_hash_config.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/date_shift_config.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/field_metadata.ex
  clients/health_care/lib/google_api/health_care/v1beta1/model/parser_config.ex
  clients/health_care/mix.exs
  clients/health_care/synth.metadata
Labels: automerge

#8770 Fix a bug in storage_objects_{rewrite,copy}
  lib/google_apis/generator/elixir_generator/parameter.ex
Labels: cla: yes

#8919 Regenerate AlertCenter client
  clients/alert_center/README.md
  clients/alert_center/lib/google_api/alert_center/v1beta1/metadata.ex
  clients/alert_center/lib/google_api/alert_center/v1beta1/model/apps_outage.ex
  clients/alert_center/lib/google_api/alert_center/v1beta1/model/merge_info.ex
  clients/alert_center/mix.exs
  clients/alert_center/synth.metadata
Labels: automerge

#8918 Regenerate Admin client
  clients/admin/lib/google_api/admin/datatransfer_v1/metadata.ex
  clients/admin/lib/google_api/admin/directory_v1/api/mobiledevices.ex
  clients/admin/lib/google_api/admin/directory_v1/metadata.ex
  clients/admin/lib/google_api/admin/reports_v1/metadata.ex
  clients/admin/mix.exs
  clients/admin/synth.metadata
Labels: automerge

#8920 Regenerate Chat client
  clients/chat/lib/google_api/chat/v1/metadata.ex
  clients/chat/lib/google_api/chat/v1/model/membership.ex
  clients/chat/lib/google_api/chat/v1/model/user.ex
  clients/chat/mix.exs
  clients/chat/synth.metadata
Labels: automerge

#8921 Regenerate CloudDeploy client
  clients/cloud_deploy/README.md
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/metadata.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/rollout.ex
  clients/cloud_deploy/lib/google_api/cloud_deploy/v1/model/target_render.ex
  clients/cloud_deploy/mix.exs
  clients/cloud_deploy/synth.metadata
Labels: automerge

#8923 Regenerate ServiceConsumerManagement client
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/metadata.ex
  clients/service_consumer_management/lib/google_api/service_consumer_management/v1/model/control.ex
  clients/service_consumer_management/mix.exs
  clients/service_consumer_management/synth.metadata
Labels: automerge

#8924 Regenerate ServiceUsage client
  clients/service_usage/lib/google_api/service_usage/v1/metadata.ex
  clients/service_usage/lib/google_api/service_usage/v1/model/control.ex
  clients/service_usage/mix.exs
  clients/service_usage/synth.metadata
Labels: automerge

#8925 Regenerate Storage client
  clients/storage/README.md
  clients/storage/lib/google_api/storage/v1/api/objects.ex
  clients/storage/lib/google_api/storage/v1/metadata.ex
  clients/storage/mix.exs
  clients/storage/synth.metadata
Labels: automerge
